export type { AssortmentScope, EffectiveAssortmentScope, ScopedProduct } from './types'
export { matchesOne } from './matchesOne'
export { matchesScope } from './matchesScope'
export { unionScopes } from './unionScopes'
export { intersectScopes } from './intersectScopes'
export { canonicalizeEffectiveScope } from './canonicalizeEffectiveScope'
export { hashEffectiveScope } from './hashEffectiveScope'
