// AUTO-GENERATED by scripts/generate-entity-ids.ts
export const M = {
  "example": "example"
} as const
export const E = {
  "example": {
    "example_item": "example:example_item",
    "todo": "example:todo"
  }
} as const
export type KnownModuleId = keyof typeof M
export type KnownEntities = typeof E
