compressionLevel: mixed

enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  "cmdk@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      "@types/react":
        optional: true
  "ts-jest@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  "@radix-ui/react-tooltip@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@testing-library/react@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "react-big-calendar@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
