import fs from 'node:fs'
import path from 'node:path'
import { spawnSync } from 'node:child_process'

import { addEnvValue, readEnvValue, replaceEnvLine, uncommentEnvLine, writeEnvFileText } from './env-file.mjs'
import { secretFingerprint, secretHex } from './secrets.mjs'

// Node port of the Windows launcher's Initialize-EnvFiles: fill-missing-only,
// secrets are generated once and never overwritten on re-runs, and postgres
// credentials are only generated while no initialized data volume exists yet
// (changing them afterwards would break auth against the data inside it).

function postgresVolumeExists() {
  const result = spawnSync('docker', ['volume', 'ls', '--format', '{{.Name}}'], { encoding: 'utf8' })
  if (result.error || result.status !== 0) return false
  return String(result.stdout ?? '')
    .split('\n')
    .map((line) => line.trim())
    .includes('mercato-postgres-data')
}

export function ensureEnvFiles(repoRoot, { log = console.log, warn = console.warn, extraDefaults = {} } = {}) {
  const rootEnv = path.join(repoRoot, '.env')
  const appEnvExample = path.join(repoRoot, 'apps', 'mercato', '.env.example')
  const appEnv = path.join(repoRoot, 'apps', 'mercato', '.env')

  const volumeExists = postgresVolumeExists()

  if (!fs.existsSync(rootEnv)) {
    writeEnvFileText(rootEnv, '# Open Mercato compose environment (generated by the hybrid starter)\n')
    log(`Created ${rootEnv}`)
  }

  let jwtSecret = readEnvValue(rootEnv, 'JWT_SECRET')
  if (!jwtSecret || !jwtSecret.trim()) jwtSecret = secretHex(32)

  const setSecret = (key, value) => {
    if (addEnvValue(rootEnv, key, value)) log(`  set ${key} (${secretFingerprint(value)})`)
  }
  const setValue = (key, value) => {
    if (addEnvValue(rootEnv, key, value)) log(`  set ${key}=${value}`)
  }

  setSecret('JWT_SECRET', jwtSecret)
  setSecret('TENANT_DATA_ENCRYPTION_FALLBACK_KEY', secretHex(16))
  const meiliKey = readEnvValue(rootEnv, 'MEILISEARCH_MASTER_KEY')?.trim() || secretHex(16)
  setSecret('MEILISEARCH_MASTER_KEY', meiliKey)
  setValue('APP_URL', `http://localhost:${readEnvValue(rootEnv, 'APP_PORT')?.trim() || '3000'}`)
  setValue('OM_INIT_SUPERADMIN_EMAIL', 'superadmin@acme.com')
  for (const [key, value] of Object.entries(extraDefaults)) {
    setValue(key, value)
  }

  let postgresPassword = readEnvValue(rootEnv, 'POSTGRES_PASSWORD')?.trim() || ''
  if (volumeExists) {
    if (readEnvValue(rootEnv, 'OM_INIT_SUPERADMIN_PASSWORD') === null) {
      warn('Existing postgres volume detected — keeping compose default credentials. Remove the mercato-postgres-data volume for a clean slate.')
    }
    if (!postgresPassword) {
      warn('Existing postgres volume but no POSTGRES_PASSWORD in .env — the app will try the compose default (postgres), which only works if the volume was created with it.')
    }
  } else {
    setSecret('OM_INIT_SUPERADMIN_PASSWORD', secretHex(8))
    if (!postgresPassword) {
      postgresPassword = secretHex(16)
      setSecret('POSTGRES_PASSWORD', postgresPassword)
    }
  }
  // NOTE: MCP_SERVER_API_KEY is intentionally NOT generated here. `yarn dev`
  // provisions a real DB-backed key into .mercato/mcp-shared; a random env
  // value would shadow it and break OpenCode -> MCP authentication.

  if (!fs.existsSync(appEnv)) {
    if (fs.existsSync(appEnvExample)) {
      let content = fs.readFileSync(appEnvExample, 'utf8')
      content = replaceEnvLine(content, 'JWT_SECRET', jwtSecret)
      content = replaceEnvLine(content, 'AUTH_SECRET', secretHex(32))
      content = replaceEnvLine(content, 'LOOKUP_HASH_PEPPER', secretHex(16))
      if (postgresPassword) {
        // 127.0.0.1, never `localhost`: on modern Windows localhost resolves
        // to ::1 first while the published container ports listen on IPv4.
        content = replaceEnvLine(
          content,
          'DATABASE_URL',
          `postgres://postgres:${postgresPassword}@127.0.0.1:5432/open-mercato`,
        )
      }
      // The hybrid starter runs a meilisearch container, so point the app at it
      // (the example ships these commented out).
      content = uncommentEnvLine(content, 'MEILISEARCH_HOST', 'http://127.0.0.1:7700')
      content = uncommentEnvLine(content, 'MEILISEARCH_API_KEY', meiliKey)
      writeEnvFileText(appEnv, content)
      log(`Created ${appEnv} from .env.example (placeholder secrets replaced)`)
    } else {
      warn('apps/mercato/.env.example not found; skipping app .env creation')
    }
  } else {
    log('apps/mercato/.env already exists (left untouched)')
  }

  return { rootEnv, appEnv, jwtSecret }
}
