import type { GeneratorPlugin } from '@open-mercato/shared/modules/generators'

function buildDataQualityTargetsOutput({
  importSection,
  entriesLiteral,
}: {
  importSection: string
  entriesLiteral: string
}): string {
  return `// AUTO-GENERATED by mercato generate registry
import type { DataQualityTarget, DataQualityGeneratedRegistry } from '@open-mercato/shared/modules/data-quality'
${importSection ? `\n${importSection}\n` : '\n'}type DataQualityTargetEntry = { moduleId: string; targets: DataQualityTarget[] }

export const dataQualityTargetEntries: DataQualityTargetEntry[] = [
${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]

export const dataQualityRegistry: DataQualityGeneratedRegistry = {
  targets: dataQualityTargetEntries.flatMap((entry) => entry.targets),
}

export default dataQualityRegistry
`
}

const dataQualityTargetsPlugin: GeneratorPlugin = {
  id: 'data_quality.targets',
  conventionFile: 'data-quality.ts',
  importPrefix: 'DATA_QUALITY_TARGETS',
  configExpr: (importName: string, moduleId: string) =>
    `{ moduleId: '${moduleId}', targets: ((${importName}.default ?? ${importName}.dataQualityConfig)?.targets ?? []) as DataQualityTarget[] }`,
  outputFileName: 'data-quality.generated.ts',
  buildOutput: buildDataQualityTargetsOutput,
  bootstrapRegistration: {
    entriesExportName: 'dataQualityTargetEntries',
    registrationImports: [
      `import { registerDataQualityTargetEntries } from '@open-mercato/core/modules/data_quality/lib/targetRegistry'`,
    ],
    buildCall: (entriesExportName: string) => `registerDataQualityTargetEntries(${entriesExportName})`,
  },
}

export const generatorPlugins: GeneratorPlugin[] = [dataQualityTargetsPlugin]

export default generatorPlugins
