// AUTO-GENERATED by scripts/generate-module-di.ts
import * as D_auth_0 from '@/modules/auth/di'
import * as D_directory_1 from '@/modules/directory/di'
import * as D_example_2 from '@/modules/example/di'

export const diRegistrars = [
  D_auth_0.register,
  D_directory_1.register,
  D_example_2.register
].filter(Boolean) as (((c: any) => void)|undefined)[]
