// AUTO-GENERATED by scripts/generate-module-entities.ts
import * as E_auth_0 from '@/modules/auth/data/entities'
import * as E_directory_1 from '@/modules/directory/data/entities'
import * as E_example_2 from '@/modules/example/data/entities'

export const entities = [
  ...Object.values(E_auth_0).filter(v => typeof v === 'function') as any[],
  ...Object.values(E_directory_1).filter(v => typeof v === 'function') as any[],
  ...Object.values(E_example_2).filter(v => typeof v === 'function') as any[]
]
