// AUTO-GENERATED by scripts/generate-module-registry.ts
import type { Module } from './registry'
import * as I0_auth from '@/modules/auth/index'
import C1_auth_reset__token_ from '@/modules/auth/frontend/reset/[token]/page'
import C2_auth_login from '@/modules/auth/frontend/login'
import C3_auth_reset from '@/modules/auth/frontend/reset'
import * as M5_auth_index from '@/modules/auth/backend/page.meta'
import C4_auth_index from '@/modules/auth/backend/page'
import * as R6_auth_login from '@/modules/auth/api/login'
import * as R7_auth_logout from '@/modules/auth/api/logout'
import * as R8_auth_reset_confirm from '@/modules/auth/api/reset/confirm'
import * as R9_auth_reset from '@/modules/auth/api/reset'
import * as R10_auth_session_refresh from '@/modules/auth/api/session/refresh'
import CLI_auth from '@/modules/auth/cli'
import T_auth_en from '@/modules/auth/i18n/en.json'
import T_auth_pl from '@/modules/auth/i18n/pl.json'
import * as I11_directory from '@/modules/directory/index'
import * as I12_example from '@/modules/example/index'
import C13_example_blog__id_ from '@/modules/example/frontend/blog/[id]/page'
import C14_example_example from '@/modules/example/frontend/example'
import C15_example_blog__id_ from '@/modules/example/backend/blog/[id]/page'
import * as M17_example_example from '@/modules/example/backend/example.meta'
import C16_example_example from '@/modules/example/backend/example'
import * as R18_example_blog__id_ from '@/modules/example/api/blog/[id]/route'
import CLI_example from '@/modules/example/cli'
import T_example_en from '@/modules/example/i18n/en.json'
import T_example_pl from '@/modules/example/i18n/pl.json'

export const modules: Module[] = [
  {
      id: 'auth',
      info: I0_auth.metadata ?? I0_auth.default,
      frontendRoutes: [{ pattern: '/reset/[token]', requireAuth: (undefined)?.requireAuth, requireRoles: (undefined)?.requireRoles, title: (undefined)?.pageTitle ?? (undefined)?.title, group: (undefined)?.pageGroup ?? (undefined)?.group, visible: (undefined)?.visible, enabled: (undefined)?.enabled, Component: C1_auth_reset__token_ }, { pattern: '/login', requireAuth: (undefined)?.requireAuth, requireRoles: (undefined)?.requireRoles, title: (undefined)?.pageTitle ?? (undefined)?.title, group: (undefined)?.pageGroup ?? (undefined)?.group, visible: (undefined)?.visible, enabled: (undefined)?.enabled, Component: C2_auth_login }, { pattern: '/reset', requireAuth: (undefined)?.requireAuth, requireRoles: (undefined)?.requireRoles, title: (undefined)?.pageTitle ?? (undefined)?.title, group: (undefined)?.pageGroup ?? (undefined)?.group, visible: (undefined)?.visible, enabled: (undefined)?.enabled, Component: C3_auth_reset }],
      backendRoutes: [{ pattern: '/backend/auth', requireAuth: (M5_auth_index.metadata)?.requireAuth, requireRoles: (M5_auth_index.metadata)?.requireRoles, title: (M5_auth_index.metadata)?.pageTitle ?? (M5_auth_index.metadata)?.title, group: (M5_auth_index.metadata)?.pageGroup ?? (M5_auth_index.metadata)?.group, visible: (M5_auth_index.metadata)?.visible, enabled: (M5_auth_index.metadata)?.enabled, Component: C4_auth_index }],
      apis: [{ path: '/auth/login', requireAuth: R6_auth_login.metadata?.requireAuth, requireRoles: R6_auth_login.metadata?.requireRoles, handlers: R6_auth_login }, { path: '/auth/logout', requireAuth: R7_auth_logout.metadata?.requireAuth, requireRoles: R7_auth_logout.metadata?.requireRoles, handlers: R7_auth_logout }, { path: '/auth/reset/confirm', requireAuth: R8_auth_reset_confirm.metadata?.requireAuth, requireRoles: R8_auth_reset_confirm.metadata?.requireRoles, handlers: R8_auth_reset_confirm }, { path: '/auth/reset', requireAuth: R9_auth_reset.metadata?.requireAuth, requireRoles: R9_auth_reset.metadata?.requireRoles, handlers: R9_auth_reset }, { path: '/auth/session/refresh', requireAuth: R10_auth_session_refresh.metadata?.requireAuth, requireRoles: R10_auth_session_refresh.metadata?.requireRoles, handlers: R10_auth_session_refresh }],
      cli: CLI_auth,
      translations: { 'en': T_auth_en as Record<string,string>, 'pl': T_auth_pl as Record<string,string> },
    },
  {
      id: 'directory',
      info: I11_directory.metadata ?? I11_directory.default,
      
      
      
      
      
    },
  {
      id: 'example',
      info: I12_example.metadata ?? I12_example.default,
      frontendRoutes: [{ pattern: '/blog/[id]', requireAuth: (undefined)?.requireAuth, requireRoles: (undefined)?.requireRoles, title: (undefined)?.pageTitle ?? (undefined)?.title, group: (undefined)?.pageGroup ?? (undefined)?.group, visible: (undefined)?.visible, enabled: (undefined)?.enabled, Component: C13_example_blog__id_ }, { pattern: '/example', requireAuth: (undefined)?.requireAuth, requireRoles: (undefined)?.requireRoles, title: (undefined)?.pageTitle ?? (undefined)?.title, group: (undefined)?.pageGroup ?? (undefined)?.group, visible: (undefined)?.visible, enabled: (undefined)?.enabled, Component: C14_example_example }],
      backendRoutes: [{ pattern: '/backend/blog/[id]', requireAuth: (undefined)?.requireAuth, requireRoles: (undefined)?.requireRoles, title: (undefined)?.pageTitle ?? (undefined)?.title, group: (undefined)?.pageGroup ?? (undefined)?.group, visible: (undefined)?.visible, enabled: (undefined)?.enabled, Component: C15_example_blog__id_ }, { pattern: '/backend/example', requireAuth: (M17_example_example.metadata)?.requireAuth, requireRoles: (M17_example_example.metadata)?.requireRoles, title: (M17_example_example.metadata)?.pageTitle ?? (M17_example_example.metadata)?.title, group: (M17_example_example.metadata)?.pageGroup ?? (M17_example_example.metadata)?.group, visible: (M17_example_example.metadata)?.visible, enabled: (M17_example_example.metadata)?.enabled, Component: C16_example_example }],
      apis: [{ path: '/example/blog/[id]', requireAuth: R18_example_blog__id_.metadata?.requireAuth, requireRoles: R18_example_blog__id_.metadata?.requireRoles, handlers: R18_example_blog__id_ }],
      cli: CLI_example,
      translations: { 'en': T_example_en as Record<string,string>, 'pl': T_example_pl as Record<string,string> },
    }
]
export const modulesInfo = modules.map(m => ({ id: m.id, ...(m.info || {}) }))
