import assert from 'node:assert/strict';
import test from 'node:test';
import { MockLanguageModelV4 } from 'ai/test';
import { dynamicTool, jsonSchema } from 'ai';
import { VercelAiAgentEngine } from '../src/runtime/engine.js';

test('Vercel AI SDK engine returns text and normalized usage', async () => {
  const model = new MockLanguageModelV4({
    doGenerate: {
      content: [{ type: 'text', text: 'approved' }],
      finishReason: { unified: 'stop', raw: undefined },
      usage: {
        inputTokens: { total: 11, noCache: 11, cacheRead: 0, cacheWrite: 0 },
        outputTokens: { total: 2, text: 2, reasoning: 0 },
      },
      warnings: [],
    },
  });
  const result = await new VercelAiAgentEngine().run({
    runId: 'run-engine',
    model,
    instructions: 'Return a short decision.',
    prompt: 'Review it.',
    tools: {},
    output: { mode: 'text' },
    settings: {},
    providerOptions: { openai: { strictJsonSchema: false } },
    maxSteps: 3,
    signal: new AbortController().signal,
  });
  assert.equal(result.output, 'approved');
  assert.deepEqual(result.usage, { inputTokens: 11, outputTokens: 2, totalTokens: 13 });
  assert.equal(result.steps, 1);
  assert.deepEqual(model.doGenerateCalls[0]?.providerOptions, {
    openai: { strictJsonSchema: false },
  });
});

test('Vercel AI SDK engine executes a dynamic tool loop and validates object output', async () => {
  let toolInput: unknown;
  const usage = {
    inputTokens: { total: 5, noCache: 5, cacheRead: 0, cacheWrite: 0 },
    outputTokens: { total: 3, text: 3, reasoning: 0 },
  };
  const model = new MockLanguageModelV4({
    doGenerate: [
      {
        content: [
          {
            type: 'tool-call',
            toolCallId: 'call-1',
            toolName: 'lookup',
            input: '{"id":"invoice-1"}',
            dynamic: true,
          },
        ],
        finishReason: { unified: 'tool-calls', raw: undefined },
        usage,
        warnings: [],
      },
      {
        content: [{ type: 'text', text: '{"decision":"approve"}' }],
        finishReason: { unified: 'stop', raw: undefined },
        usage,
        warnings: [],
      },
    ],
  });
  const result = await new VercelAiAgentEngine().run({
    runId: 'run-tool-loop',
    model,
    instructions: 'Look up the invoice and decide.',
    prompt: 'Review invoice-1.',
    tools: {
      lookup: dynamicTool({
        inputSchema: jsonSchema({
          type: 'object',
          properties: { id: { type: 'string' } },
          required: ['id'],
          additionalProperties: false,
        }),
        execute: async (input) => {
          toolInput = input;
          return { status: 'ready' };
        },
      }),
    },
    output: {
      mode: 'object',
      schema: {
        type: 'object',
        properties: { decision: { type: 'string', enum: ['approve', 'reject'] } },
        required: ['decision'],
        additionalProperties: false,
      },
    },
    settings: {},
    maxSteps: 3,
    signal: new AbortController().signal,
  });
  assert.deepEqual(toolInput, { id: 'invoice-1' });
  assert.deepEqual(result.output, { decision: 'approve' });
  assert.equal(result.steps, 2);
});

test('Vercel AI SDK engine accepts draft 2020-12 output schemas generated by Open Mercato', async () => {
  const model = new MockLanguageModelV4({
    doGenerate: {
      content: [
        {
          type: 'text',
          text: '{"kind":"proposal","proposal":{"actions":[{"type":"set_stage","payload":{"stage":"qualified"}}],"confidence":0.9,"rationale":"Healthy deal"}}',
        },
      ],
      finishReason: { unified: 'stop', raw: undefined },
      usage: {
        inputTokens: { total: 7, noCache: 7, cacheRead: 0, cacheWrite: 0 },
        outputTokens: { total: 12, text: 12, reasoning: 0 },
      },
      warnings: [],
    },
  });
  const result = await new VercelAiAgentEngine().run({
    runId: 'run-draft-2020-12',
    model,
    instructions: 'Return a deal health proposal.',
    prompt: 'Review the deal.',
    tools: {},
    output: {
      mode: 'object',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          kind: { type: 'string', const: 'proposal' },
          proposal: {
            type: 'object',
            properties: {
              actions: {
                type: 'array',
                minItems: 1,
                items: {
                  type: 'object',
                  properties: {
                    type: { type: 'string', const: 'set_stage' },
                    payload: {
                      type: 'object',
                      properties: { stage: { type: 'string', minLength: 1 } },
                      required: ['stage'],
                      additionalProperties: false,
                    },
                  },
                  required: ['type', 'payload'],
                  additionalProperties: false,
                },
              },
              confidence: { type: 'number', minimum: 0, maximum: 1 },
              rationale: { type: 'string', minLength: 1 },
            },
            required: ['actions', 'confidence', 'rationale'],
            additionalProperties: false,
          },
        },
        required: ['kind', 'proposal'],
        additionalProperties: false,
      },
    },
    settings: {},
    maxSteps: 3,
    signal: new AbortController().signal,
  });
  assert.deepEqual(result.output, {
    kind: 'proposal',
    proposal: {
      actions: [{ type: 'set_stage', payload: { stage: 'qualified' } }],
      confidence: 0.9,
      rationale: 'Healthy deal',
    },
  });
});
