import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import type { ModuleScanContext } from '../extension'
import { createAgentFilesExtension } from '../extensions/agent-files'

/**
 * Build a fake repo root with the package markers used by `findRepoRoot` and
 * extension's `findRepoRoot` resolves it) and a module whose `agents/<id>/`
 * fixture lives under `appBase`.
 */
function makeRepoFixture(): { repoRoot: string; appBase: string; pkgBase: string } {
  const repoRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-files-repo-'))
  fs.writeFileSync(path.join(repoRoot, 'package.json'), '{}', 'utf8')
  fs.mkdirSync(path.join(repoRoot, 'packages', 'enterprise'), { recursive: true })

  const appBase = path.join(repoRoot, 'apps', 'mercato', 'src', 'modules', 'agent_examples')
  const pkgBase = path.join(repoRoot, 'packages', 'core', 'src', 'modules', 'agent_examples')
  const agentDir = path.join(appBase, 'agents', 'deals_health_check')
  fs.mkdirSync(agentDir, { recursive: true })

  fs.writeFileSync(
    path.join(agentDir, 'AGENT.md'),
    [
      '---',
      'id: deals.health_check',
      'label: Deal health check',
      'description: Assess a deal.',
      'maxSteps: 12',
      '---',
      'You assess a deal.',
    ].join('\n'),
    'utf8',
  )
  fs.writeFileSync(
    path.join(agentDir, 'OUTCOME.md'),
    [
      '---',
      'kind: proposal',
      '---',
      '```json',
      JSON.stringify({
        type: 'object',
        required: ['confidence'],
        properties: { confidence: { type: 'number', minimum: 0, maximum: 1 } },
      }),
      '```',
    ].join('\n'),
    'utf8',
  )

  return { repoRoot, appBase, pkgBase }
}

function createScanContext(moduleId: string, appBase: string, pkgBase: string): ModuleScanContext {
  return {
    moduleId,
    roots: { appBase, pkgBase },
    imps: { appBase: `@/modules/${moduleId}`, pkgBase: `@open-mercato/core/modules/${moduleId}` },
    importIdRef: { value: 0 },
    sharedImports: [],
    resolveModuleFile: (() => null) as ModuleScanContext['resolveModuleFile'],
    resolveFirstModuleFile: (() => null) as ModuleScanContext['resolveFirstModuleFile'],
    processStandaloneConfig: () => null,
    sanitizeGeneratedModuleSpecifier: (importPath) => importPath,
  }
}

describe('createAgentFilesExtension', () => {
  let repoRoot = ''
  afterEach(() => {
    if (repoRoot) fs.rmSync(repoRoot, { recursive: true, force: true })
    repoRoot = ''
  })

  it('discovers agents/<id>/ and emits only the runtime-neutral manifest', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot

    const extension = createAgentFilesExtension()
    expect(extension.id).toBe('registry.agent-files')

    extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
    const output = extension.generateOutput()
    expect(output.size).toBe(0)

    const manifestPath = path.join(
      repoRoot,
      'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts',
    )
    expect(fs.existsSync(manifestPath)).toBe(true)
    const manifest = fs.readFileSync(manifestPath, 'utf8')
    expect(manifest).toContain('AUTO-GENERATED by mercato generate registry')
    expect(manifest).toContain("id: \"deals.health_check\"")
    expect(manifest).not.toContain('openCodeAgentName')
    expect(manifest).toContain('export const fileAgentDescriptors')
    expect(fs.existsSync(path.join(repoRoot, 'docker'))).toBe(false)
  })

  it('nests sub-agent descriptors without generating runtime-specific files', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')

    // Declare a sub-agent under sub-agents/<subid>/ (researcher + non-delegating).
    fs.writeFileSync(
      path.join(agentDir, 'AGENT.md'),
      [
        '---',
        'id: deals.health_check',
        'label: Deal health check',
        'description: Assess a deal.',
        '---',
        'You assess a deal.',
      ].join('\n'),
      'utf8',
    )
    const subDir = path.join(agentDir, 'sub-agents', 'company_researcher')
    fs.mkdirSync(subDir, { recursive: true })
    fs.writeFileSync(
      path.join(subDir, 'AGENT.md'),
      [
        '---',
        'id: deals.company_researcher',
        'label: Company researcher',
        'description: Research a company.',
        '---',
        'You research a company.',
      ].join('\n'),
      'utf8',
    )
    fs.writeFileSync(
      path.join(subDir, 'OUTCOME.md'),
      [
        '---',
        'kind: researcher',
        '---',
        '```json',
        JSON.stringify({ type: 'object', properties: { summary: { type: 'string' } } }),
        '```',
      ].join('\n'),
      'utf8',
    )

    const extension = createAgentFilesExtension()
    extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
    extension.generateOutput()

    const manifest = fs.readFileSync(
      path.join(repoRoot, 'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts'),
      'utf8',
    )
    expect(manifest).toContain('subAgentDescriptors')
    expect(manifest).toContain('deals.company_researcher')
    expect(fs.existsSync(path.join(repoRoot, 'docker'))).toBe(false)
  })

  it('emits an agent SAMPLE.json into the manifest as sampleInput', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(
      path.join(agentDir, 'SAMPLE.json'),
      JSON.stringify({ deal: { id: 'demo-deal-1', stage: 'Proposal' } }),
      'utf8',
    )

    const extension = createAgentFilesExtension()
    extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
    extension.generateOutput()

    const manifest = fs.readFileSync(
      path.join(repoRoot, 'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts'),
      'utf8',
    )
    expect(manifest).toContain('sampleInput: {"deal":{"id":"demo-deal-1","stage":"Proposal"}}')
  })

  it('fails generation on a malformed SAMPLE.json', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(path.join(agentDir, 'SAMPLE.json'), '{ not valid json', 'utf8')

    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/malformed SAMPLE\.json/)
  })

  it('emits an agent FACTS.json into the manifest as facts', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(
      path.join(agentDir, 'FACTS.json'),
      JSON.stringify({
        facts: [
          { label: 'Stage', source: 'input', path: 'deal.stage' },
          { label: 'Confidence', source: 'payload', path: 'confidence', format: 'percent' },
        ],
      }),
      'utf8',
    )

    const extension = createAgentFilesExtension()
    extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
    extension.generateOutput()

    const manifest = fs.readFileSync(
      path.join(repoRoot, 'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts'),
      'utf8',
    )
    expect(manifest).toContain(
      'facts: [{"label":"Stage","source":"input","path":"deal.stage"},{"label":"Confidence","source":"payload","path":"confidence","format":"percent"}]',
    )
    expect(manifest).toContain('export type FileAgentFact')
  })

  it('fails generation on a FACTS.json entry missing label/source/path', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(
      path.join(agentDir, 'FACTS.json'),
      JSON.stringify({ facts: [{ label: 'Stage', source: 'nowhere', path: 'deal.stage' }] }),
      'utf8',
    )

    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/malformed FACTS\.json/)
  })

  it('fails generation on a malformed agent dir (missing OUTCOME.md)', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    // Remove OUTCOME.md to make the dir malformed.
    fs.rmSync(path.join(fixture.appBase, 'agents', 'deals_health_check', 'OUTCOME.md'))

    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/malformed file agent/)
  })

  it('unions skill tools and writes skillsContent to the manifest', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')

    // Reference a skill in AGENT.md and author it under skills/<skill_id>/.
    fs.writeFileSync(
      path.join(agentDir, 'AGENT.md'),
      [
        '---',
        'id: deals.health_check',
        'label: Deal health check',
        'description: Assess a deal.',
        'skills: [stage_playbook]',
        'tools: [customers.get_deal]',
        '---',
        'You assess a deal.',
      ].join('\n'),
      'utf8',
    )
    const skillDir = path.join(agentDir, 'skills', 'stage_playbook')
    fs.mkdirSync(path.join(skillDir, 'examples'), { recursive: true })
    fs.writeFileSync(
      path.join(skillDir, 'SKILL.md'),
      [
        '---',
        'id: stage_playbook',
        'label: Stage playbook',
        'description: Pick the next stage.',
        'tools: [customers.analyze_deals]',
        '---',
        'STAGE_PLAYBOOK_BODY',
      ].join('\n'),
      'utf8',
    )
    fs.writeFileSync(path.join(skillDir, 'TEMPLATE.md'), 'TEMPLATE_BODY', 'utf8')
    fs.writeFileSync(path.join(skillDir, 'examples', 'a.md'), 'EXAMPLE_ONE', 'utf8')

    const extension = createAgentFilesExtension()
    extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
    extension.generateOutput()

    // Manifest carries skillsContent and the unioned tool allowlist.
    const manifest = fs.readFileSync(
      path.join(repoRoot, 'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts'),
      'utf8',
    )
    expect(manifest).toContain('skillsContent')
    expect(manifest).toContain('STAGE_PLAYBOOK_BODY')
    expect(manifest).toContain('TEMPLATE_BODY')
    expect(manifest).toContain('EXAMPLE_ONE')
    expect(manifest).toContain('customers.analyze_deals')

    expect(fs.existsSync(path.join(repoRoot, 'docker'))).toBe(false)
  })

  it('fails generation on a malformed SKILL.md (no frontmatter)', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(
      path.join(agentDir, 'AGENT.md'),
      [
        '---',
        'id: deals.health_check',
        'label: Deal health check',
        'description: Assess a deal.',
        'skills: [stage_playbook]',
        '---',
        'You assess a deal.',
      ].join('\n'),
      'utf8',
    )
    const skillDir = path.join(agentDir, 'skills', 'stage_playbook')
    fs.mkdirSync(skillDir, { recursive: true })
    fs.writeFileSync(path.join(skillDir, 'SKILL.md'), 'no frontmatter at all', 'utf8')

    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/malformed SKILL\.md/)
  })

  it('fails generation when an OUTCOME.md schema is outside the supported subset (M2)', () => {
    const fixture = makeRepoFixture()
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    // `oneOf` parses as valid JSON but cannot compile to Zod — must fail at scan,
    // not silently parse and get dropped at load.
    fs.writeFileSync(
      path.join(agentDir, 'OUTCOME.md'),
      [
        '---',
        'kind: proposal',
        '---',
        '```json',
        JSON.stringify({ type: 'object', properties: { x: { oneOf: [{ type: 'string' }] } } }),
        '```',
      ].join('\n'),
      'utf8',
    )
    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/unsupported keyword "oneOf"/)
  })

  it('fails generation when an OUTCOME.md schema node has no supported type (M2)', () => {
    const fixture = makeRepoFixture()
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(
      path.join(agentDir, 'OUTCOME.md'),
      [
        '---',
        'kind: researcher',
        '---',
        '```json',
        JSON.stringify({ type: 'object', properties: { x: { minimum: 0 } } }),
        '```',
      ].join('\n'),
      'utf8',
    )
    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/missing\/unsupported "type"/)
  })

  it('keeps committed agent artifacts when neither the orchestrator nor an agent module is enabled', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const manifestPath = path.join(
      repoRoot,
      'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts',
    )
    fs.mkdirSync(path.dirname(manifestPath), { recursive: true })
    fs.writeFileSync(manifestPath, 'committed manifest', 'utf8')

    const extension = createAgentFilesExtension()
    // A module with no `agents/` tree, standing in for a run with the
    // enterprise agents flag off.
    const otherBase = path.join(repoRoot, 'packages', 'core', 'src', 'modules', 'customers')
    fs.mkdirSync(otherBase, { recursive: true })
    extension.scanModule(createScanContext('customers', otherBase, otherBase))
    extension.generateOutput()

    expect(fs.readFileSync(manifestPath, 'utf8')).toBe('committed manifest')
  })

  it('writes an empty manifest when the orchestrator is enabled without any agent', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const extension = createAgentFilesExtension()
    const orchestratorBase = path.join(
      repoRoot,
      'packages',
      'enterprise',
      'src',
      'modules',
      'agent_orchestrator',
    )
    fs.mkdirSync(orchestratorBase, { recursive: true })
    extension.scanModule(createScanContext('agent_orchestrator', orchestratorBase, orchestratorBase))
    extension.generateOutput()

    const manifest = fs.readFileSync(
      path.join(
        repoRoot,
        'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts',
      ),
      'utf8',
    )
    expect(manifest).toContain('export const fileAgentDescriptors: FileAgentDescriptor[] = []')
  })
})
