import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import type { ModuleScanContext } from '../extension'
import { createAgentFilesExtension } from '../extensions/agent-files'

/**
 * Build a fake repo root with `docker/opencode` + `packages` markers (so the
 * extension's `findRepoRoot` resolves it) and a module whose `agents/<id>/`
 * fixture lives under `appBase`.
 */
function makeRepoFixture(): { repoRoot: string; appBase: string; pkgBase: string } {
  const repoRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-files-repo-'))
  fs.mkdirSync(path.join(repoRoot, 'docker', 'opencode'), { recursive: true })
  fs.mkdirSync(path.join(repoRoot, 'packages'), { recursive: true })

  const appBase = path.join(repoRoot, 'apps', 'mercato', 'src', 'modules', 'agent_examples')
  const pkgBase = path.join(repoRoot, 'packages', 'core', 'src', 'modules', 'agent_examples')
  const agentDir = path.join(appBase, 'agents', 'deals_health_check')
  fs.mkdirSync(agentDir, { recursive: true })

  fs.writeFileSync(
    path.join(agentDir, 'CLAUDE.md'),
    [
      '---',
      'id: deals.health_check',
      'label: Deal health check',
      'description: Assess a deal.',
      'maxSteps: 12',
      '---',
      'You assess a deal.',
    ].join('\n'),
    'utf8',
  )
  fs.writeFileSync(
    path.join(agentDir, 'OUTCOME.md'),
    [
      '---',
      'kind: actionable',
      '---',
      '```json',
      JSON.stringify({
        type: 'object',
        required: ['confidence'],
        properties: { confidence: { type: 'number', minimum: 0, maximum: 1 } },
      }),
      '```',
    ].join('\n'),
    'utf8',
  )

  return { repoRoot, appBase, pkgBase }
}

function createScanContext(moduleId: string, appBase: string, pkgBase: string): ModuleScanContext {
  return {
    moduleId,
    roots: { appBase, pkgBase },
    imps: { appBase: `@/modules/${moduleId}`, pkgBase: `@open-mercato/core/modules/${moduleId}` },
    importIdRef: { value: 0 },
    sharedImports: [],
    resolveModuleFile: (() => null) as ModuleScanContext['resolveModuleFile'],
    resolveFirstModuleFile: (() => null) as ModuleScanContext['resolveFirstModuleFile'],
    processStandaloneConfig: () => null,
    sanitizeGeneratedModuleSpecifier: (importPath) => importPath,
  }
}

describe('createAgentFilesExtension', () => {
  let repoRoot = ''
  afterEach(() => {
    if (repoRoot) fs.rmSync(repoRoot, { recursive: true, force: true })
    repoRoot = ''
  })

  it('discovers agents/<id>/ and emits the manifest + docker agent file', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot

    const extension = createAgentFilesExtension()
    expect(extension.id).toBe('registry.agent-files')

    extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
    const output = extension.generateOutput()
    expect(output.size).toBe(0)

    const manifestPath = path.join(
      repoRoot,
      'packages/core/src/modules/agent_orchestrator/generated/file-agents.generated.ts',
    )
    expect(fs.existsSync(manifestPath)).toBe(true)
    const manifest = fs.readFileSync(manifestPath, 'utf8')
    expect(manifest).toContain('AUTO-GENERATED by mercato generate registry')
    expect(manifest).toContain("id: \"deals.health_check\"")
    expect(manifest).toContain("openCodeAgentName: \"deals_health_check\"")
    expect(manifest).toContain('export const fileAgentDescriptors')

    const dockerFile = path.join(repoRoot, 'docker/opencode/agents/deals_health_check.md')
    expect(fs.existsSync(dockerFile)).toBe(true)
    const dockerContent = fs.readFileSync(dockerFile, 'utf8')
    expect(dockerContent).toContain('mode: primary')
    expect(dockerContent).toContain('agent_orchestrator.submit_outcome')
    expect(dockerContent).toContain('write: deny')
  })

  it('fails generation on a malformed agent dir (missing OUTCOME.md)', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    // Remove OUTCOME.md to make the dir malformed.
    fs.rmSync(path.join(fixture.appBase, 'agents', 'deals_health_check', 'OUTCOME.md'))

    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/malformed file agent/)
  })
})
