import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import type { ModuleScanContext } from '../extension'
import { createAgentFilesExtension } from '../extensions/agent-files'

/**
 * Build a fake repo root with `docker/opencode` + `packages` markers (so the
 * extension's `findRepoRoot` resolves it) and a module whose `agents/<id>/`
 * fixture lives under `appBase`.
 */
function makeRepoFixture(): { repoRoot: string; appBase: string; pkgBase: string } {
  const repoRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-files-repo-'))
  fs.mkdirSync(path.join(repoRoot, 'docker', 'opencode'), { recursive: true })
  fs.mkdirSync(path.join(repoRoot, 'packages'), { recursive: true })

  const appBase = path.join(repoRoot, 'apps', 'mercato', 'src', 'modules', 'agent_examples')
  const pkgBase = path.join(repoRoot, 'packages', 'core', 'src', 'modules', 'agent_examples')
  const agentDir = path.join(appBase, 'agents', 'deals_health_check')
  fs.mkdirSync(agentDir, { recursive: true })

  fs.writeFileSync(
    path.join(agentDir, 'AGENT.md'),
    [
      '---',
      'id: deals.health_check',
      'label: Deal health check',
      'description: Assess a deal.',
      'maxSteps: 12',
      '---',
      'You assess a deal.',
    ].join('\n'),
    'utf8',
  )
  fs.writeFileSync(
    path.join(agentDir, 'OUTCOME.md'),
    [
      '---',
      'kind: actionable',
      '---',
      '```json',
      JSON.stringify({
        type: 'object',
        required: ['confidence'],
        properties: { confidence: { type: 'number', minimum: 0, maximum: 1 } },
      }),
      '```',
    ].join('\n'),
    'utf8',
  )

  return { repoRoot, appBase, pkgBase }
}

function createScanContext(moduleId: string, appBase: string, pkgBase: string): ModuleScanContext {
  return {
    moduleId,
    roots: { appBase, pkgBase },
    imps: { appBase: `@/modules/${moduleId}`, pkgBase: `@open-mercato/core/modules/${moduleId}` },
    importIdRef: { value: 0 },
    sharedImports: [],
    resolveModuleFile: (() => null) as ModuleScanContext['resolveModuleFile'],
    resolveFirstModuleFile: (() => null) as ModuleScanContext['resolveFirstModuleFile'],
    processStandaloneConfig: () => null,
    sanitizeGeneratedModuleSpecifier: (importPath) => importPath,
  }
}

describe('createAgentFilesExtension', () => {
  let repoRoot = ''
  afterEach(() => {
    if (repoRoot) fs.rmSync(repoRoot, { recursive: true, force: true })
    repoRoot = ''
  })

  it('discovers agents/<id>/ and emits the manifest + docker agent file', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot

    const extension = createAgentFilesExtension()
    expect(extension.id).toBe('registry.agent-files')

    extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
    const output = extension.generateOutput()
    expect(output.size).toBe(0)

    const manifestPath = path.join(
      repoRoot,
      'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts',
    )
    expect(fs.existsSync(manifestPath)).toBe(true)
    const manifest = fs.readFileSync(manifestPath, 'utf8')
    expect(manifest).toContain('AUTO-GENERATED by mercato generate registry')
    expect(manifest).toContain("id: \"deals.health_check\"")
    expect(manifest).toContain("openCodeAgentName: \"deals_health_check\"")
    expect(manifest).toContain('export const fileAgentDescriptors')

    const dockerFile = path.join(repoRoot, 'docker/opencode/agents/deals_health_check.md')
    expect(fs.existsSync(dockerFile)).toBe(true)
    const dockerContent = fs.readFileSync(dockerFile, 'utf8')
    expect(dockerContent).toContain('mode: primary')
    expect(dockerContent).toContain('open-mercato_agent_orchestrator_submit_outcome')
    expect(dockerContent).toContain('write: deny')
  })

  it('emits an agent SAMPLE.json into the manifest as sampleInput', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(
      path.join(agentDir, 'SAMPLE.json'),
      JSON.stringify({ deal: { id: 'demo-deal-1', stage: 'Proposal' } }),
      'utf8',
    )

    const extension = createAgentFilesExtension()
    extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
    extension.generateOutput()

    const manifest = fs.readFileSync(
      path.join(repoRoot, 'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts'),
      'utf8',
    )
    expect(manifest).toContain('sampleInput: {"deal":{"id":"demo-deal-1","stage":"Proposal"}}')
  })

  it('fails generation on a malformed SAMPLE.json', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(path.join(agentDir, 'SAMPLE.json'), '{ not valid json', 'utf8')

    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/malformed SAMPLE\.json/)
  })

  it('emits an agent FACTS.json into the manifest as facts', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(
      path.join(agentDir, 'FACTS.json'),
      JSON.stringify({
        facts: [
          { label: 'Stage', source: 'input', path: 'deal.stage' },
          { label: 'Confidence', source: 'payload', path: 'confidence', format: 'percent' },
        ],
      }),
      'utf8',
    )

    const extension = createAgentFilesExtension()
    extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
    extension.generateOutput()

    const manifest = fs.readFileSync(
      path.join(repoRoot, 'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts'),
      'utf8',
    )
    expect(manifest).toContain(
      'facts: [{"label":"Stage","source":"input","path":"deal.stage"},{"label":"Confidence","source":"payload","path":"confidence","format":"percent"}]',
    )
    expect(manifest).toContain('export type FileAgentFact')
  })

  it('fails generation on a FACTS.json entry missing label/source/path', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(
      path.join(agentDir, 'FACTS.json'),
      JSON.stringify({ facts: [{ label: 'Stage', source: 'nowhere', path: 'deal.stage' }] }),
      'utf8',
    )

    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/malformed FACTS\.json/)
  })

  it('fails generation on a malformed agent dir (missing OUTCOME.md)', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    // Remove OUTCOME.md to make the dir malformed.
    fs.rmSync(path.join(fixture.appBase, 'agents', 'deals_health_check', 'OUTCOME.md'))

    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/malformed file agent/)
  })

  it('emits native SKILL.md, unions skill tools, and writes skillsContent to the manifest', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')

    // Reference a skill in AGENT.md and author it under skills/<skill_id>/.
    fs.writeFileSync(
      path.join(agentDir, 'AGENT.md'),
      [
        '---',
        'id: deals.health_check',
        'label: Deal health check',
        'description: Assess a deal.',
        'skills: [stage_playbook]',
        'tools: [customers.get_deal]',
        '---',
        'You assess a deal.',
      ].join('\n'),
      'utf8',
    )
    const skillDir = path.join(agentDir, 'skills', 'stage_playbook')
    fs.mkdirSync(path.join(skillDir, 'examples'), { recursive: true })
    fs.writeFileSync(
      path.join(skillDir, 'SKILL.md'),
      [
        '---',
        'id: stage_playbook',
        'label: Stage playbook',
        'description: Pick the next stage.',
        'tools: [customers.analyze_deals]',
        '---',
        'STAGE_PLAYBOOK_BODY',
      ].join('\n'),
      'utf8',
    )
    fs.writeFileSync(path.join(skillDir, 'TEMPLATE.md'), 'TEMPLATE_BODY', 'utf8')
    fs.writeFileSync(path.join(skillDir, 'examples', 'a.md'), 'EXAMPLE_ONE', 'utf8')

    const extension = createAgentFilesExtension()
    extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
    extension.generateOutput()

    // Native OpenCode skill file (sanitized dir name: stage_playbook → stage-playbook).
    const nativeSkill = path.join(repoRoot, 'docker/opencode/skills/stage-playbook/SKILL.md')
    expect(fs.existsSync(nativeSkill)).toBe(true)
    const nativeContent = fs.readFileSync(nativeSkill, 'utf8')
    expect(nativeContent).toContain('name: stage-playbook')
    expect(nativeContent).toContain('STAGE_PLAYBOOK_BODY')

    // Manifest carries skillsContent and the unioned tool allowlist.
    const manifest = fs.readFileSync(
      path.join(repoRoot, 'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts'),
      'utf8',
    )
    expect(manifest).toContain('skillsContent')
    expect(manifest).toContain('STAGE_PLAYBOOK_BODY')
    expect(manifest).toContain('TEMPLATE_BODY')
    expect(manifest).toContain('EXAMPLE_ONE')
    expect(manifest).toContain('customers.analyze_deals')

    // The docker agent file's tools block includes the skill tool too.
    const dockerAgent = fs.readFileSync(
      path.join(repoRoot, 'docker/opencode/agents/deals_health_check.md'),
      'utf8',
    )
    // Declared OM tool ids are mapped to OpenCode's MCP tool id form in the allowlist.
    expect(dockerAgent).toContain('open-mercato_customers_analyze_deals')
  })

  it('fails generation on a malformed SKILL.md (no frontmatter)', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(
      path.join(agentDir, 'AGENT.md'),
      [
        '---',
        'id: deals.health_check',
        'label: Deal health check',
        'description: Assess a deal.',
        'skills: [stage_playbook]',
        '---',
        'You assess a deal.',
      ].join('\n'),
      'utf8',
    )
    const skillDir = path.join(agentDir, 'skills', 'stage_playbook')
    fs.mkdirSync(skillDir, { recursive: true })
    fs.writeFileSync(path.join(skillDir, 'SKILL.md'), 'no frontmatter at all', 'utf8')

    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/malformed SKILL\.md/)
  })

  it('fails generation when an OUTCOME.md schema is outside the supported subset (M2)', () => {
    const fixture = makeRepoFixture()
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    // `oneOf` parses as valid JSON but cannot compile to Zod — must fail at scan,
    // not silently parse and get dropped at load.
    fs.writeFileSync(
      path.join(agentDir, 'OUTCOME.md'),
      [
        '---',
        'kind: actionable',
        '---',
        '```json',
        JSON.stringify({ type: 'object', properties: { x: { oneOf: [{ type: 'string' }] } } }),
        '```',
      ].join('\n'),
      'utf8',
    )
    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/unsupported keyword "oneOf"/)
  })

  it('fails generation when an OUTCOME.md schema node has no supported type (M2)', () => {
    const fixture = makeRepoFixture()
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(
      path.join(agentDir, 'OUTCOME.md'),
      [
        '---',
        'kind: informative',
        '---',
        '```json',
        JSON.stringify({ type: 'object', properties: { x: { minimum: 0 } } }),
        '```',
      ].join('\n'),
      'utf8',
    )
    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/missing\/unsupported "type"/)
  })
})
