import vm from 'node:vm'
import ts from 'typescript'
import { CodeBlockWriter, VariableDeclarationKind, type WriterFunction } from 'ts-morph'
import { arrayLiteral, identifier, writeValue } from '../ast'
import {
  defaultImportSpec,
  dynamicImportExpression,
  emptyArray,
  emptyObject,
  fallbackChain,
  moduleEntry,
  namespaceFallback,
  namespaceImportSpec,
  namespaceMember,
  parenthesizedNamespaceMember,
  renderGeneratedTsSource,
  sideEffectImportSpec,
} from '../extensions/shared'

function renderWriter(writerFunction: WriterFunction): string {
  const writer = new CodeBlockWriter({
    indentNumberOfSpaces: 2,
    newLine: '\n',
    useSingleQuote: false,
    useTabs: false,
  })
  writerFunction(writer)
  return writer.toString()
}

function parseDiagnostics(source: string): string[] {
  const sourceFile = ts.createSourceFile('generated.ts', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
  return sourceFile.parseDiagnostics.map((diagnostic) =>
    ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n'),
  )
}

function evaluateExpression(expression: string, globals: Record<string, unknown>): unknown {
  const source = `result = ${expression};`
  const compiled = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2020,
    },
  }).outputText

  const context = { result: undefined as unknown, ...globals }
  vm.runInNewContext(compiled, context)
  return context.result
}

describe('generator extension shared helpers', () => {
  it('renders generated TypeScript with header, imports, and no stale state', () => {
    const firstOutput = renderGeneratedTsSource({
      fileName: 'shared.generated.ts',
      build(sourceFile) {
        sourceFile.addVariableStatement({
          declarationKind: VariableDeclarationKind.Const,
          isExported: true,
          declarations: [
            {
              name: 'firstPass',
              initializer: 'true',
            },
          ],
        })
      },
    })

    const secondOutput = renderGeneratedTsSource({
      fileName: 'shared.generated.ts',
      generator: 'extensions',
      imports: [
        namespaceImportSpec('CONFIG', '@/modules/example/config'),
        defaultImportSpec('DemoWidget', '@/modules/example/widget'),
        sideEffectImportSpec('@/modules/example/setup'),
      ],
      build(sourceFile) {
        sourceFile.addVariableStatement({
          declarationKind: VariableDeclarationKind.Const,
          isExported: true,
          declarations: [
            {
              name: 'entries',
              initializer: arrayLiteral(
                [
                  moduleEntry('example', [
                    { name: 'config', value: namespaceMember('CONFIG', 'default') },
                    { name: 'widget', value: identifier('DemoWidget') },
                  ]),
                ],
                writeValue,
              ),
            },
          ],
        })
      },
    })

    expect(firstOutput).toContain('export const firstPass = true;')
    expect(secondOutput.startsWith('// AUTO-GENERATED by mercato generate extensions\n')).toBe(true)
    expect(secondOutput).toContain('import * as CONFIG from "@/modules/example/config";')
    expect(secondOutput).toContain('import DemoWidget from "@/modules/example/widget";')
    expect(secondOutput).toContain('import "@/modules/example/setup";')
    expect(secondOutput).toContain('moduleId: "example"')
    expect(secondOutput).not.toContain('firstPass')
    expect(secondOutput.endsWith('\n')).toBe(true)
    expect(parseDiagnostics(secondOutput)).toEqual([])
  })

  it('returns the expected import spec objects', () => {
    expect(namespaceImportSpec('CONFIG', '@/config')).toEqual({
      moduleSpecifier: '@/config',
      namespaceImport: 'CONFIG',
    })
    expect(defaultImportSpec('DemoWidget', '@/widget')).toEqual({
      defaultImport: 'DemoWidget',
      moduleSpecifier: '@/widget',
    })
    expect(sideEffectImportSpec('@/setup')).toEqual({
      moduleSpecifier: '@/setup',
    })
  })

  it('renders utility writer helpers as expected', () => {
    expect(renderWriter(namespaceMember('MODULE', 'config'))).toBe('MODULE.config')
    expect(renderWriter(parenthesizedNamespaceMember('MODULE', 'config'))).toBe('(MODULE.config)')
    expect(renderWriter(fallbackChain([identifier('first'), identifier('second'), identifier('third')]))).toBe(
      'first ?? second ?? third',
    )
    expect(renderWriter(emptyArray())).toBe('[]')
    expect(renderWriter(emptyObject())).toBe('{}')
    expect(renderWriter(dynamicImportExpression('@/widgets/demo'))).toBe('import("@/widgets/demo")')

    const entry = renderWriter(
      moduleEntry('example', [
        { name: 'config', value: identifier('resolvedConfig') },
        { name: 'loader', value: dynamicImportExpression('@/widgets/demo') },
      ]),
    )

    expect(entry).toContain('moduleId: "example"')
    expect(entry).toContain('config: resolvedConfig')
    expect(entry).toContain('loader: import("@/widgets/demo")')
  })

  it('namespaceFallback preserves falsey exports and only falls back on nullish values', () => {
    const castExpression = renderWriter(
      namespaceFallback({
        importName: 'MODULE',
        members: ['default', 'config'],
        fallback: identifier('fallbackValue'),
        castType: 'unknown',
      }),
    )

    expect(castExpression).toContain('as unknown')
    expect(evaluateExpression(castExpression, { MODULE: { default: 0, config: 7 }, fallbackValue: 'fallback' })).toBe(0)
    expect(evaluateExpression(castExpression, { MODULE: { default: null, config: false }, fallbackValue: 'fallback' })).toBe(false)
    expect(
      evaluateExpression(castExpression, { MODULE: { default: null, config: undefined }, fallbackValue: 'fallback' }),
    ).toBe('fallback')

    const uncastExpression = renderWriter(
      namespaceFallback({
        importName: 'MODULE',
        members: ['config'],
        fallback: emptyArray(),
      }),
    )

    expect(uncastExpression).not.toContain('as unknown')
    expect(evaluateExpression(uncastExpression, { MODULE: {} })).toEqual([])
  })
})
