// Pure source emitter for src/backend/icons/lucideRegistry.generated.tsx.
// Kept side-effect free, and CommonJS so both build.mjs and the Jest suite can load it.

function sortResolvedIcons(resolvedIcons) {
  return [...resolvedIcons].sort((a, b) => a.kebab.localeCompare(b.kebab))
}

function collectUniqueExports(resolvedIcons) {
  return [...new Set(resolvedIcons.map((icon) => icon.exportName))].sort((a, b) => a.localeCompare(b))
}

function buildLucideRegistrySource(resolvedIcons) {
  const entries = sortResolvedIcons(resolvedIcons)
  const uniqueExports = collectUniqueExports(entries)

  const importSection = uniqueExports.length
    ? `import {\n${uniqueExports.map((name) => `  ${name},`).join('\n')}\n} from 'lucide-react'\n`
    : ``

  const registryEntries = entries.map((icon) => `  '${icon.kebab}': ${icon.exportName},`).join('\n')

  return `/* eslint-disable */
// AUTO-GENERATED by @open-mercato/ui build. Do not edit by hand.
// Generated from discovered icon string usages across the repo.

import type { LucideIcon } from 'lucide-react'
${importSection}
export const LUCIDE_ICON_REGISTRY: Record<string, LucideIcon> = {
${registryEntries ? `${registryEntries}\n` : ''}}
`
}

module.exports = { buildLucideRegistrySource }
