export const DEFAULT_ENCRYPTION_MAPS: Array<{ entityId: string; fields: Array<{ field: string; hashField?: string | null }> }> = [
  {
    entityId: 'auth:user',
    fields: [{ field: 'email', hashField: 'emailHash' }],
  },
  {
    entityId: 'customers:customer_address',
    fields: [
      { field: 'name' },
      { field: 'companyName' },
      { field: 'addressLine1' },
      { field: 'addressLine2' },
      { field: 'city' },
      { field: 'region' },
      { field: 'postalCode' },
      { field: 'country' },
      { field: 'buildingNumber' },
      { field: 'flatNumber' },
    ],
  },
  {
    entityId: 'customers:customer_comment',
    fields: [{ field: 'body' }],
  },
  {
    entityId: 'customers:customer_person_profile',
    fields: [
      { field: 'firstName' },
      { field: 'lastName' },
      { field: 'preferredName' },
      { field: 'jobTitle' },
      { field: 'department' },
      { field: 'seniority' },
      { field: 'timezone' },
      { field: 'linkedInUrl' },
      { field: 'twitterUrl' },
    ],
  },
  {
    entityId: 'sales:sales_order',
    fields: [
      { field: 'customerSnapshot' },
      { field: 'billingAddressSnapshot' },
      { field: 'shippingAddressSnapshot' },
      { field: 'shippingMethodSnapshot' },
      { field: 'deliveryWindowSnapshot' },
      { field: 'paymentMethodSnapshot' },
      { field: 'totalsSnapshot' },
      { field: 'catalogSnapshot' },
      { field: 'promotionSnapshot' },
      { field: 'comments' },
      { field: 'internalNotes' },
    ],
  },
  {
    entityId: 'sales:sales_quote',
    fields: [
      { field: 'customerSnapshot' },
      { field: 'billingAddressSnapshot' },
      { field: 'shippingAddressSnapshot' },
      { field: 'shippingMethodSnapshot' },
      { field: 'deliveryWindowSnapshot' },
      { field: 'paymentMethodSnapshot' },
      { field: 'totalsSnapshot' },
      { field: 'catalogSnapshot' },
      { field: 'promotionSnapshot' },
      { field: 'itemsSnapshot' },
      { field: 'comments' },
      { field: 'internalNotes' },
    ],
  },
  {
    entityId: 'sales:sales_note',
    fields: [{ field: 'body' }],
  },
]
