// AUTO-GENERATED by scripts/generate-entity-ids.ts
export const M = {
  "auth": "auth",
  "directory": "directory",
  "custom_fields": "custom_fields"
} as const
export const E = {
  "auth": {
    "password_reset": "auth:password_reset",
    "role": "auth:role",
    "session": "auth:session",
    "user": "auth:user",
    "user_role": "auth:user_role"
  },
  "directory": {
    "organization": "directory:organization",
    "tenant": "directory:tenant"
  },
  "custom_fields": {
    "custom_field_def": "custom_fields:custom_field_def",
    "custom_field_value": "custom_fields:custom_field_value"
  }
} as const
export type KnownModuleId = keyof typeof M
export type KnownEntities = typeof E
