import { expect, test } from '@playwright/test'
import vm from 'node:vm'
import ts from 'typescript'
import { CodeBlockWriter, VariableDeclarationKind, type WriterFunction } from 'ts-morph'
import { arrayLiteral, identifier, writeValue } from '../../../../../../../packages/cli/src/lib/generators/ast'
import {
  dynamicImportExpression,
  emptyArray,
  moduleEntry,
  namespaceFallback,
  namespaceImportSpec,
  renderGeneratedTsSource,
} from '../../../../../../../packages/cli/src/lib/generators/extensions/shared'

function renderWriter(writerFunction: WriterFunction): string {
  const writer = new CodeBlockWriter({
    indentNumberOfSpaces: 2,
    newLine: '\n',
    useSingleQuote: false,
    useTabs: false,
  })
  writerFunction(writer)
  return writer.toString()
}

function parseDiagnostics(source: string): string[] {
  const sourceFile = ts.createSourceFile('registry.generated.ts', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
  return sourceFile.parseDiagnostics.map((diagnostic) =>
    ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n'),
  )
}

function evaluateExpression(expression: string, globals: Record<string, unknown>): unknown {
  const compiled = ts.transpileModule(`result = ${expression};`, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2020,
    },
  }).outputText

  const context = { result: undefined as unknown, ...globals }
  vm.runInNewContext(compiled, context)
  return context.result
}

test.describe('TC-UMES-021: CLI generator shared helper contract', () => {
  test('renders parseable registry source through the package export path', () => {
    const source = renderGeneratedTsSource({
      fileName: 'registry.generated.ts',
      imports: [namespaceImportSpec('EXAMPLE', '@/modules/example/config')],
      build(sourceFile) {
        sourceFile.addVariableStatement({
          declarationKind: VariableDeclarationKind.Const,
          isExported: true,
          declarations: [
            {
              name: 'registryEntries',
              initializer: arrayLiteral(
                [
                  moduleEntry('example', [
                    {
                      name: 'config',
                      value: namespaceFallback({
                        importName: 'EXAMPLE',
                        members: ['default', 'config'],
                        fallback: emptyArray(),
                        castType: 'unknown[]',
                      }),
                    },
                    {
                      name: 'loader',
                      value: dynamicImportExpression('@/modules/example/widgets/dashboard/todos/widget'),
                    },
                  ]),
                ],
                writeValue,
              ),
            },
          ],
        })
      },
    })

    expect(source.startsWith('// AUTO-GENERATED by mercato generate registry\n')).toBe(true)
    expect(source).toContain('import * as EXAMPLE from "@/modules/example/config";')
    expect(source).toContain('moduleId: "example"')
    expect(source).toMatch(/"default"[\s,]+"config"/)
    expect(source).toContain('import("@/modules/example/widgets/dashboard/todos/widget")')
    expect(parseDiagnostics(source)).toEqual([])
  })

  test('namespaceFallback keeps falsey exports and only falls back on nullish values', () => {
    const expression = renderWriter(
      namespaceFallback({
        importName: 'MODULE',
        members: ['default', 'config'],
        fallback: identifier('fallbackValue'),
        castType: 'unknown',
      }),
    )

    expect(evaluateExpression(expression, { MODULE: { default: 0, config: 5 }, fallbackValue: 'fallback' })).toBe(0)
    expect(evaluateExpression(expression, { MODULE: { default: null, config: false }, fallbackValue: 'fallback' })).toBe(false)
    expect(
      evaluateExpression(expression, { MODULE: { default: undefined, config: null }, fallbackValue: 'fallback' }),
    ).toBe('fallback')
  })
})
