/**
 * Module-declared generator plugin.
 *
 * `generators.ts` is the only auto-discovered file that extends `mercato generate`
 * itself: `generateModuleRegistry` imports it from every enabled module before it
 * walks the modules, so a plugin declared here collects a convention file from EVERY
 * enabled module, not just this one. Use it when a contribution must be resolved
 * statically at build time — the alternative registries (DI, widgets, subscribers)
 * all resolve at runtime and cannot be inspected by the generator.
 *
 * The three parts have to exist together or the plugin is inert:
 *
 * 1. this declaration,
 * 2. the module-root convention file it aggregates
 *    (`example-todo-preview-fields.ts`; this module ships its own),
 * 3. a live consumer of the registry the `bootstrapRegistration` populates
 *    (`lib/messageObjectPreviews.ts`, reached from `message-objects.ts`).
 *
 * `bootstrapRegistration` is what removes the last manual step: the generator appends
 * the import and the call to `bootstrap-registrations.generated.ts`, so `bootstrap.ts`
 * never names this module. Its `registrationImports` are emitted verbatim into
 * `<app>/.mercato/generated/`, which is always two levels below the app root — hence
 * the `../../src/modules/...` specifier, the same shape the registry generator already
 * emits for `@app` modules.
 */
import type { GeneratorPlugin } from '@open-mercato/shared/modules/generators'

const REGISTRY_IMPORT_PATH = '../../src/modules/example/lib/todoPreviewFields'

function buildTodoPreviewFieldsOutput({
  importSection,
  entriesLiteral,
}: {
  importSection: string
  entriesLiteral: string
}): string {
  return `// AUTO-GENERATED by mercato generate registry
import type { TodoPreviewField, TodoPreviewFieldModuleEntry } from '${REGISTRY_IMPORT_PATH}'
${importSection ? `${importSection}\n` : ''}
export const todoPreviewFieldEntries: TodoPreviewFieldModuleEntry[] = [
${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]
`
}

const todoPreviewFieldsPlugin: GeneratorPlugin = {
  id: 'example.todo-preview-fields',
  conventionFile: 'example-todo-preview-fields.ts',
  importPrefix: 'EXAMPLE_TODO_PREVIEW_FIELDS',
  configExpr: (importName: string, moduleId: string) =>
    `{ moduleId: '${moduleId}', fields: ((${importName}.default ?? ${importName}.todoPreviewFields ?? []) as TodoPreviewField[]) }`,
  outputFileName: 'example-todo-preview-fields.generated.ts',
  buildOutput: buildTodoPreviewFieldsOutput,
  bootstrapRegistration: {
    entriesExportName: 'todoPreviewFieldEntries',
    registrationImports: [
      `import { registerTodoPreviewFieldEntries } from '${REGISTRY_IMPORT_PATH}'`,
    ],
    buildCall: (name: string) => `registerTodoPreviewFieldEntries(${name})`,
  },
}

export const generatorPlugins: GeneratorPlugin[] = [todoPreviewFieldsPlugin]

export default generatorPlugins
