#!/usr/bin/env node
import { spawnSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

// The gate runs before `yarn install` in CI (`--check-lockfile`) and right
// after it, so this script must stay dependency-free: Node built-ins only.
export const GATE_STEPS = Object.freeze(['generate', 'typecheck', 'lint', 'ds:check', 'test', 'build'])

// `typecheck` already ran `tsc`, and Next's in-build type check re-runs it in a
// worker while the main process holds the compiled graph, which is OOM-killed
// on a 7 GB runner. next.config.ts skips that check only when this is set.
export const SKIP_NEXT_BUILD_TYPECHECK_ENV = 'OM_SKIP_NEXT_BUILD_TYPECHECK'

export const STUB_LOCKFILE_MESSAGE =
  'yarn.lock is still the placeholder generated by create-mercato-app. Run "yarn install" locally and commit yarn.lock.'

export const USAGE = [
  'Usage: node scripts/ci.mjs [--prepare-env | --check-lockfile]',
  '',
  '  (no flag)         Prepare .env, then run the quality gate: ' + GATE_STEPS.join(' → '),
  '  --prepare-env     Copy .env.example to .env when .env is absent (never overwrites)',
  '  --check-lockfile  Fail when yarn.lock is missing or still the scaffold placeholder',
].join('\n')

export function stepEnv(step, baseEnv = process.env) {
  if (step !== 'build') return baseEnv
  return { ...baseEnv, [SKIP_NEXT_BUILD_TYPECHECK_ENV]: '1' }
}

export function formatDuration(milliseconds) {
  const totalSeconds = milliseconds / 1000
  if (totalSeconds < 60) return `${totalSeconds.toFixed(1)}s`
  const minutes = Math.floor(totalSeconds / 60)
  const seconds = Math.round(totalSeconds - minutes * 60)
  return `${minutes}m ${seconds}s`
}

export function runYarnStep(step, { cwd = process.cwd(), env = process.env } = {}) {
  const result = spawnSync('yarn', ['run', step], {
    cwd,
    env,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  })
  if (result.error) {
    process.stderr.write(`[ci] could not start "yarn run ${step}": ${result.error.message}\n`)
    return 1
  }
  return typeof result.status === 'number' ? result.status : 1
}

export function runGate({
  steps = GATE_STEPS,
  runStep = runYarnStep,
  log = (line) => {
    process.stdout.write(`${line}\n`)
  },
  logError = (line) => {
    process.stderr.write(`${line}\n`)
  },
  cwd = process.cwd(),
  env = process.env,
  now = () => Date.now(),
} = {}) {
  const gateStartedAt = now()
  for (const [index, step] of steps.entries()) {
    log(`\n[ci] ▶ ${step} (${index + 1}/${steps.length})`)
    const stepStartedAt = now()
    const exitCode = runStep(step, { cwd, env: stepEnv(step, env) })
    const duration = formatDuration(now() - stepStartedAt)
    if (exitCode !== 0) {
      const reportedExitCode = Number.isInteger(exitCode) && exitCode > 0 ? exitCode : 1
      logError(`[ci] ✗ ${step} failed after ${duration}`)
      logError(`yarn ci failed at "${step}" (exit ${reportedExitCode})`)
      return { ok: false, failedStep: step, exitCode: reportedExitCode }
    }
    log(`[ci] ✓ ${step} passed in ${duration}`)
  }
  log(`\n✅ yarn ci passed: ${steps.length} steps in ${formatDuration(now() - gateStartedAt)}`)
  return { ok: true, failedStep: null, exitCode: 0 }
}

export function prepareEnv({
  rootDir = process.cwd(),
  log = (line) => {
    process.stdout.write(`${line}\n`)
  },
} = {}) {
  const envPath = path.join(rootDir, '.env')
  const examplePath = path.join(rootDir, '.env.example')
  if (fs.existsSync(envPath)) {
    log('[ci] .env already exists, leaving it untouched')
    return { created: false, reason: 'exists' }
  }
  if (!fs.existsSync(examplePath)) {
    log('[ci] no .env or .env.example found, nothing to prepare')
    return { created: false, reason: 'missing-example' }
  }
  try {
    fs.copyFileSync(examplePath, envPath, fs.constants.COPYFILE_EXCL)
  } catch (error) {
    if (error && error.code === 'EEXIST') {
      log('[ci] .env already exists, leaving it untouched')
      return { created: false, reason: 'exists' }
    }
    throw error
  }
  log('[ci] created .env from .env.example')
  return { created: true, reason: 'created' }
}

export function listLockfileEntries(contents) {
  const entries = []
  for (const line of contents.split(/\r?\n/)) {
    if (line.length === 0 || /^\s/.test(line) || line.startsWith('#')) continue
    const trimmed = line.trimEnd()
    if (!trimmed.endsWith(':')) continue
    entries.push(trimmed.slice(0, -1).replace(/^"(.*)"$/, '$1'))
  }
  return entries
}

export function isStubLockfile(contents) {
  const packageEntries = listLockfileEntries(contents).filter(
    (entry) => entry !== '__metadata' && !entry.endsWith('@workspace:.'),
  )
  return packageEntries.length === 0
}

export function checkLockfile({ rootDir = process.cwd() } = {}) {
  const lockfilePath = path.join(rootDir, 'yarn.lock')
  if (!fs.existsSync(lockfilePath)) return { ok: false, message: STUB_LOCKFILE_MESSAGE }
  if (isStubLockfile(fs.readFileSync(lockfilePath, 'utf8'))) return { ok: false, message: STUB_LOCKFILE_MESSAGE }
  return { ok: true, message: '[ci] yarn.lock contains resolved packages' }
}

export function main(argv = process.argv.slice(2), { rootDir = process.cwd() } = {}) {
  if (argv.length > 1) {
    process.stderr.write(`${USAGE}\n`)
    return 2
  }
  const [flag] = argv
  if (flag === '--help' || flag === '-h') {
    process.stdout.write(`${USAGE}\n`)
    return 0
  }
  if (flag === '--prepare-env') {
    prepareEnv({ rootDir })
    return 0
  }
  if (flag === '--check-lockfile') {
    const result = checkLockfile({ rootDir })
    if (result.ok) {
      process.stdout.write(`${result.message}\n`)
      return 0
    }
    process.stderr.write(`${result.message}\n`)
    return 1
  }
  if (flag !== undefined) {
    process.stderr.write(`Unknown option: ${flag}\n\n${USAGE}\n`)
    return 2
  }
  prepareEnv({ rootDir })
  return runGate({ cwd: rootDir }).exitCode
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exitCode = main()
}
