/**
 * Self-contained agentic setup for the CLI `agentic:init` command.
 *
 * This duplicates the generator logic from packages/create-app/src/setup/
 * because standalone apps cannot import from create-app at runtime.
 * Content is embedded as strings to avoid external file dependencies.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, dirname, basename } from 'node:path'

type AskFn = (question: string) => Promise<string>

interface AgenticSetupOptions {
  tool?: string
  force?: boolean
}

interface AgenticConfig {
  projectName: string
  targetDir: string
}

// ─── Shared content ──────────────────────────────────────────────────────

const AGENTS_TEMPLATE = `# Agent Context Routing — {{PROJECT_NAME}}

Read this file before any task. Load ONLY the files listed for your task type.
Do NOT load the entire src/ tree — Open Mercato apps can have many modules.

## What this project is

A standalone Open Mercato application. You are building domain features ON TOP of
the Open Mercato framework — not modifying the framework itself.

The framework lives in node_modules/@open-mercato/*. To customise a built-in module
beyond what the extension system supports, eject it with \`yarn mercato eject <module>\`.
Never edit node_modules directly.

## Task → Context map

| Task | Load these files |
|---|---|
| Add a new custom module | \`src/modules.ts\`, one existing \`src/modules/<id>/index.ts\` as reference |
| Add/modify an entity | \`src/modules/<id>/entities/\`, \`src/modules/<id>/migrations/\` |
| Add a REST API endpoint | \`src/modules/<id>/api/\`, \`src/modules/<id>/routes.ts\` |
| Add a backend page | \`src/modules/<id>/backend/\`, \`src/modules/<id>/routes.ts\` |
| Register a DI service | \`src/modules/<id>/di.ts\` |
| Add an event subscriber | \`src/modules/<id>/subscribers/\`, \`src/modules/<id>/index.ts\` |
| Add a CLI command | \`src/modules/<id>/cli/\` |
| Add widget injection | \`src/modules/<id>/widgets/injection/\`, \`src/modules/<id>/widgets/injection-table.ts\` |
| Add a response enricher | \`src/modules/<id>/data/enrichers.ts\` |
| Add an API interceptor | \`src/modules/<id>/api/interceptors.ts\` |
| Eject a core module | Run \`yarn mercato eject <module-id>\` |
| Write a spec | \`.ai/specs/README.md\`, \`.ai/specs/SPEC-000-template.md\` |

## Critical conventions

- After any module or entity change: \`yarn generate\`
- After any entity edit: create migration with \`yarn db:generate\`
- NEVER edit \`.mercato/generated/*\` — auto-generated by \`yarn generate\`
- NEVER directly edit files in \`node_modules/@open-mercato/*\` — eject instead
- Custom modules: \`from: '@app'\` in \`src/modules.ts\`
- Confirm migrations with the user before running \`yarn db:migrate\`

## Module anatomy

Each module in \`src/modules/<id>/\` is self-contained:

| Directory/File | Purpose |
|---|---|
| \`entities/\` | MikroORM entity classes |
| \`migrations/\` | Per-module migration files |
| \`api/\` | REST handlers (auto-discovered by method + path) |
| \`backend/\` | Admin UI pages (auto-discovered) |
| \`frontend/\` | Public pages (auto-discovered) |
| \`di.ts\` | Awilix DI registrations |
| \`acl.ts\` | Feature-based permissions |
| \`setup.ts\` | Tenant initialization, role features |
| \`events.ts\` | Typed event declarations |
| \`subscribers/\` | Domain event handlers |
| \`workers/\` | Background job handlers |
| \`widgets/injection/\` | UI widgets injected into other modules |
| \`widgets/components.ts\` | Component replacement/wrapper definitions |
| \`data/enrichers.ts\` | Response enrichers for data federation |
| \`api/interceptors.ts\` | API route interception hooks |
| \`cli/\` | Module CLI commands |
| \`search.ts\` | Search indexing configuration |

Register in \`src/modules.ts\`: \`{ id: '<id>', from: '@app' }\`

## Key commands

| Command | Purpose |
|---|---|
| \`yarn dev\` | Start dev server |
| \`yarn generate\` | Regenerate \`.mercato/generated/\` |
| \`yarn db:generate\` | Create migration for entity changes |
| \`yarn db:migrate\` | Apply pending migrations |
| \`yarn initialize\` | Bootstrap DB + first admin account |
| \`yarn build\` | Build for production |
| \`yarn mercato eject <module>\` | Copy a core module into src/modules/ |

## Stack

Next.js App Router, TypeScript, MikroORM, Awilix DI, zod
`

const SPECS_README = `# Feature Specs — {{PROJECT_NAME}}

Specs document business feature design decisions. Source of truth for what was built and why.

## What belongs here

- New domain features (inventory management, order flow, customer portal, etc.)
- Data model decisions (entity design, relationships, indexing strategy)
- API contract definitions for custom endpoints
- Integration design (external services, webhooks, import/export)

## What does NOT belong here

Framework-level decisions belong in the Open Mercato core repo. If you're unsure,
it's almost certainly an app-level decision.

## Naming convention

SPEC-{number}-{YYYY-MM-DD}-{slug}.md
Example: SPEC-001-2026-03-01-inventory-module.md

## Workflow

1. Before coding any significant feature, check for an existing spec
2. If none: create from SPEC-000-template.md, review with team, then code
3. After implementation: update the spec's Changelog and Acceptance Criteria
`

const SPEC_TEMPLATE = `# SPEC-{number} — {Title}

**Date**: {YYYY-MM-DD}
**Status**: Draft

## TLDR

{2-3 sentence summary}

## Problem Statement

{What problem this feature solves}

## Proposed Solution

{High-level approach}

## Data Models

{Entity definitions, relationships}

## API Contracts

{Endpoints, request/response schemas}

## Acceptance Criteria

- [ ] {Criterion 1}
- [ ] {Criterion 2}

## Changelog

| Date | Change |
|------|--------|
| {date} | Initial spec |
`

const LESSONS_MD = `# Lessons Learned

Record patterns, mistakes, and insights discovered during development.
AI agents will update this file as they work on the codebase.
`

// ─── Claude Code content ─────────────────────────────────────────────────

const CLAUDE_MD_TEMPLATE = `# {{PROJECT_NAME}} — Claude Code Instructions

See AGENTS.md for task → context routing before starting any task.

## What this project is

A standalone Open Mercato application. You are building domain features ON TOP of
the Open Mercato framework — not modifying the framework itself.

The framework lives in node_modules/@open-mercato/*. To customise a built-in module,
eject it with \`yarn mercato eject <module>\` — never edit node_modules directly.

## Stack

- Next.js App Router, TypeScript, MikroORM, Awilix DI, zod

## Critical rules

- NEVER edit \`.mercato/generated/*\`
- ALWAYS run \`yarn generate\` after any module or entity change
- ALWAYS confirm migrations with the user before running
- ALWAYS check \`.ai/specs/\` before implementing significant features
`

const CLAUDE_SETTINGS = `{
  "hooks": {
    "PostToolUse": [
      {
        "matcher": "Write|Edit|MultiEdit",
        "hooks": [
          {
            "type": "command",
            "command": "npx tsx \\"$CLAUDE_PROJECT_DIR/.claude/hooks/entity-migration-check.ts\\"",
            "timeout": 15
          }
        ]
      }
    ]
  }
}
`

const CLAUDE_HOOK = `/**
 * Claude Code PostToolUse hook: entity-migration-check
 *
 * Fires after Write/Edit/MultiEdit. Detects entity file modifications
 * without an accompanying migration and blocks the agent with a reminder.
 */

import { readdirSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'

const ENTITY_PATTERN = /^src\\/modules\\/([^/]+)\\/entities\\/.*\\.ts$/
const MIGRATION_PATTERN = /^src\\/modules\\/([^/]+)\\/migrations\\/.*\\.ts$/

interface PostToolUseInput {
  tool_input?: { file_path?: string }
}

function getRelativePath(filePath: string): string {
  const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd()
  if (filePath.startsWith('/')) return relative(projectDir, filePath)
  return filePath
}

function hasFreshMigration(moduleId: string): boolean {
  const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd()
  const migrationsDir = join(projectDir, 'src', 'modules', moduleId, 'migrations')
  try {
    const files = readdirSync(migrationsDir)
    const cutoff = Date.now() - 30_000
    for (const file of files) {
      if (!file.endsWith('.ts')) continue
      const stat = statSync(join(migrationsDir, file))
      if (stat.mtimeMs > cutoff) return true
    }
  } catch {}
  return false
}

async function main(): Promise<void> {
  let input = ''
  for await (const chunk of process.stdin) { input += chunk }
  if (!input.trim()) process.exit(0)

  let data: PostToolUseInput
  try { data = JSON.parse(input) } catch { process.exit(0) }

  const filePath = data.tool_input?.file_path
  if (!filePath) process.exit(0)

  const rel = getRelativePath(filePath)
  if (MIGRATION_PATTERN.test(rel)) process.exit(0)

  const entityMatch = rel.match(ENTITY_PATTERN)
  if (!entityMatch) process.exit(0)

  const moduleId = entityMatch[1]
  if (hasFreshMigration(moduleId)) process.exit(0)

  const result = {
    decision: 'block',
    reason: [
      \`Entity file modified: \${rel}\`,
      '', \`Affected module: \${moduleId}\`, '',
      'A database migration is likely needed. Ask the user whether to run:',
      '  yarn db:generate', '',
      'Then regenerate registries:', '  yarn generate', '',
      'Do NOT run migrations automatically — always confirm with the user first.',
    ].join('\\n'),
  }
  process.stdout.write(JSON.stringify(result))
}

main()
`

const MCP_EXAMPLE = `{
  "_comment": "Copy to .mcp.json and set MCP_API_KEY (printed by yarn initialize)",
  "mcpServers": {
    "open-mercato": {
      "command": "yarn",
      "args": ["mercato", "mcp:dev"],
      "env": {
        "APP_URL": "http://localhost:3000",
        "MCP_API_KEY": "\${MCP_API_KEY}"
      }
    }
  }
}
`

// ─── Codex content ───────────────────────────────────────────────────────

const CODEX_ENFORCEMENT = `<!-- CODEX_ENFORCEMENT_RULES_START -->
## CRITICAL rules — always follow without exception

1. **After editing any entity file** (\`src/modules/<id>/entities/*.ts\`):
   - STOP immediately before any further action
   - Tell the user: "I modified an entity in module <id>. Should I create a migration?"
   - If yes: run \`yarn db:generate\`
   - Show the generated migration to the user before applying
   - Ask for confirmation, then run \`yarn db:migrate\`
   - Run \`yarn generate\` after migration is applied

2. **After editing \`src/modules.ts\`**: immediately run \`yarn generate\`

3. **Never edit \`.mercato/generated/*\`**: edit the source and run \`yarn generate\` instead

4. **Before significant features**: check \`.ai/specs/\` for an existing spec.
   If none exists, ask the user whether to create one first.

---
<!-- CODEX_ENFORCEMENT_RULES_END -->
`

const CODEX_MCP = `{
  "mcpServers": {
    "open-mercato": {
      "command": "yarn",
      "args": ["mercato", "mcp:dev"],
      "env": {
        "APP_URL": "http://localhost:3000",
        "MCP_API_KEY": "\${MCP_API_KEY}"
      }
    }
  }
}
`

// ─── Cursor content ──────────────────────────────────────────────────────

const CURSOR_RULES_MAIN = `---
description: Core Open Mercato conventions for standalone app development
alwaysApply: true
---

# {{PROJECT_NAME}} — Project Rules

## What this project is

A standalone Open Mercato application. Build domain features ON TOP of the framework.
To customise a core module beyond the extension system: \`yarn mercato eject <module>\`.
Never edit node_modules/@open-mercato/* directly.

## Task routing

Read AGENTS.md before starting any task — it maps task types to the minimum files to load.

## Module system

Modules in \`src/modules/<id>/\`. Register with \`from: '@app'\` in \`src/modules.ts\`.
Run \`yarn generate\` after any module or entity change. Never edit \`.mercato/generated/*\`.

## Entity and migration rule

After editing any entity in \`src/modules/<id>/entities/\`:
1. Create migration: \`yarn db:generate\`
2. Show migration to user, confirm before applying
3. Apply: \`yarn db:migrate\`
4. Regenerate: \`yarn generate\`

## Spec-driven development

Check \`.ai/specs/\` before any significant feature. If no spec exists, ask the user
whether to create one first.
`

const CURSOR_ENTITY_GUARD = `---
description: Entity modification guard — triggers migration workflow
globs:
  - src/modules/*/entities/**/*.ts
alwaysApply: false
---

# Entity Modification — Migration Required

You are editing an entity file. After saving, you MUST:

1. **Create a migration** — ask the user before running:
   \`\`\`
   yarn db:generate
   \`\`\`

2. **Show the migration** to the user and wait for confirmation before applying

3. **Apply the migration** (only after user confirms):
   \`\`\`
   yarn db:migrate
   \`\`\`

4. **Regenerate registries**:
   \`\`\`
   yarn generate
   \`\`\`

Do NOT skip any step. Do NOT run migrations without user confirmation.
`

const CURSOR_GENERATED_GUARD = `---
description: Prevent editing auto-generated files
globs:
  - .mercato/generated/**
alwaysApply: false
---

# NEVER Edit Generated Files

This file is auto-generated by \`yarn generate\`. Any manual edits will be overwritten.

To change generated output, edit the source modules in \`src/modules/\` and run \`yarn generate\`.
`

const CURSOR_HOOKS_JSON = `{
  "version": 1,
  "hooks": {
    "afterFileEdit": {
      "command": "node",
      "args": [".cursor/hooks/entity-migration-check.mjs"],
      "description": "Check if entity edit requires a database migration"
    }
  }
}
`

const CURSOR_HOOK_MJS = `/**
 * Cursor afterFileEdit hook: entity-migration-check
 *
 * Detects entity file modifications without an accompanying migration
 * and exits non-zero to block the agent with a reminder.
 */

import { readdirSync, statSync } from 'node:fs'
import { join, resolve } from 'node:path'

const ENTITY_RE = /^src\\/modules\\/([^/]+)\\/entities\\/.*\\.ts$/
const MIGRATION_RE = /^src\\/modules\\/([^/]+)\\/migrations\\/.*\\.ts$/

function hasFreshMigration(projectDir, moduleId) {
  const migrationsDir = join(projectDir, 'src', 'modules', moduleId, 'migrations')
  try {
    const files = readdirSync(migrationsDir)
    const cutoff = Date.now() - 30_000
    for (const file of files) {
      if (!file.endsWith('.ts')) continue
      const stat = statSync(join(migrationsDir, file))
      if (stat.mtimeMs > cutoff) return true
    }
  } catch {}
  return false
}

const filePath = process.argv[2]
if (!filePath) process.exit(0)

const projectDir = resolve('.')
const rel = filePath.startsWith('/') ? filePath.slice(projectDir.length + 1) : filePath

if (MIGRATION_RE.test(rel)) process.exit(0)

const match = rel.match(ENTITY_RE)
if (!match) process.exit(0)

const moduleId = match[1]
if (hasFreshMigration(projectDir, moduleId)) process.exit(0)

process.stderr.write(
  [
    \`Entity file modified: \${rel}\`,
    '', \`Affected module: \${moduleId}\`, '',
    'A database migration is likely needed. Ask the user whether to run:',
    '  yarn db:generate', '',
    'Then regenerate registries:', '  yarn generate', '',
    'Do NOT run migrations automatically — always confirm with the user first.', '',
  ].join('\\n'),
)
process.exit(1)
`

const CURSOR_MCP = `{
  "_comment": "Copy to .cursor/mcp.json and set MCP_API_KEY (printed by yarn initialize)",
  "mcpServers": {
    "open-mercato": {
      "command": "yarn",
      "args": ["mercato", "mcp:dev"],
      "env": {
        "APP_URL": "http://localhost:3000",
        "MCP_API_KEY": "\${MCP_API_KEY}"
      }
    }
  }
}
`

// ─── Helpers ─────────────────────────────────────────────────────────────

function resolve_(content: string, config: AgenticConfig): string {
  return content.replace(/\{\{PROJECT_NAME\}\}/g, config.projectName)
}

function ensureDir(filePath: string): void {
  const dir = dirname(filePath)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
}

function writeFile(path: string, content: string): void {
  ensureDir(path)
  writeFileSync(path, content)
}

// ─── Generators ──────────────────────────────────────────────────────────

function generateShared(config: AgenticConfig): void {
  const { targetDir } = config
  writeFile(join(targetDir, 'AGENTS.md'), resolve_(AGENTS_TEMPLATE, config))
  writeFile(join(targetDir, '.ai', 'specs', 'README.md'), resolve_(SPECS_README, config))
  writeFile(join(targetDir, '.ai', 'specs', 'SPEC-000-template.md'), SPEC_TEMPLATE)
  writeFile(join(targetDir, '.ai', 'lessons.md'), LESSONS_MD)
}

function generateClaudeCode(config: AgenticConfig): void {
  const { targetDir } = config
  writeFile(join(targetDir, 'CLAUDE.md'), resolve_(CLAUDE_MD_TEMPLATE, config))
  writeFile(join(targetDir, '.claude', 'settings.json'), CLAUDE_SETTINGS)
  writeFile(join(targetDir, '.claude', 'hooks', 'entity-migration-check.ts'), CLAUDE_HOOK)
  writeFile(join(targetDir, '.mcp.json.example'), MCP_EXAMPLE)
}

function generateCodex(config: AgenticConfig): void {
  const { targetDir } = config
  const agentsPath = join(targetDir, 'AGENTS.md')

  if (existsSync(agentsPath)) {
    let agents = readFileSync(agentsPath, 'utf-8')
    const MARKER_START = '<!-- CODEX_ENFORCEMENT_RULES_START -->'
    const MARKER_END = '<!-- CODEX_ENFORCEMENT_RULES_END -->'

    if (agents.includes(MARKER_START)) {
      const startIdx = agents.indexOf(MARKER_START)
      const endIdx = agents.indexOf(MARKER_END)
      if (endIdx !== -1) {
        agents = agents.slice(0, startIdx) + CODEX_ENFORCEMENT + agents.slice(endIdx + MARKER_END.length)
      }
    } else {
      const firstNewline = agents.indexOf('\n')
      if (firstNewline !== -1) {
        agents = agents.slice(0, firstNewline + 1) + '\n' + CODEX_ENFORCEMENT + '\n' + agents.slice(firstNewline + 1)
      } else {
        agents = agents + '\n\n' + CODEX_ENFORCEMENT
      }
    }
    writeFileSync(agentsPath, agents)
  }

  writeFile(join(targetDir, '.codex', 'mcp.json.example'), CODEX_MCP)
}

function generateCursor(config: AgenticConfig): void {
  const { targetDir } = config
  writeFile(join(targetDir, '.cursor', 'rules', 'open-mercato.mdc'), resolve_(CURSOR_RULES_MAIN, config))
  writeFile(join(targetDir, '.cursor', 'rules', 'entity-guard.mdc'), CURSOR_ENTITY_GUARD)
  writeFile(join(targetDir, '.cursor', 'rules', 'generated-guard.mdc'), CURSOR_GENERATED_GUARD)
  writeFile(join(targetDir, '.cursor', 'hooks.json'), CURSOR_HOOKS_JSON)
  writeFile(join(targetDir, '.cursor', 'hooks', 'entity-migration-check.mjs'), CURSOR_HOOK_MJS)
  writeFile(join(targetDir, '.cursor', 'mcp.json.example'), CURSOR_MCP)
}

// ─── Wizard ──────────────────────────────────────────────────────────────

const TOOLS = [
  { key: '1', label: 'Claude Code     (Anthropic)', id: 'claude-code' },
  { key: '2', label: 'Codex           (OpenAI)', id: 'codex' },
  { key: '3', label: 'Cursor          (Anysphere)', id: 'cursor' },
  { key: '4', label: 'Multiple tools  (select individually)', id: 'multiple' },
  { key: '5', label: 'Skip — set up manually later', id: 'skip' },
] as const

const SELECTABLE = TOOLS.filter((t) => t.id !== 'multiple' && t.id !== 'skip')

async function promptSelection(ask: AskFn): Promise<string[]> {
  console.log('')
  console.log('🤖  Agentic workflow setup')
  console.log('')
  console.log('   Which AI coding tool will you use with this project?')
  console.log('')
  for (const tool of TOOLS) {
    console.log(`   ${tool.key}. ${tool.label}`)
  }
  console.log('')

  const answer = (await ask('   Enter number(s) separated by comma [1]: ')).trim() || '1'

  if (answer === '5') return ['skip']

  if (answer === '4') {
    const selected: string[] = []
    for (const tool of SELECTABLE) {
      const yn = await ask(`   Include ${tool.label}? [y/N]: `)
      if (yn.toLowerCase() === 'y' || yn.toLowerCase() === 'yes') {
        selected.push(tool.id)
      }
    }
    return selected.length > 0 ? selected : ['skip']
  }

  const keys = answer.split(',').map((s) => s.trim())
  const ids: string[] = []
  for (const key of keys) {
    const tool = TOOLS.find((t) => t.key === key)
    if (tool && tool.id !== 'multiple' && tool.id !== 'skip') {
      ids.push(tool.id)
    }
  }
  return ids.length > 0 ? ids : ['skip']
}

export async function runAgenticSetup(
  targetDir: string,
  ask: AskFn,
  options?: AgenticSetupOptions,
): Promise<void> {
  let selectedIds: string[]

  if (options?.tool) {
    selectedIds = options.tool.split(',').map((t) => t.trim())
  } else {
    selectedIds = await promptSelection(ask)
  }

  if (selectedIds.includes('skip')) {
    console.log('')
    console.log('   Skipped agentic setup.')
    console.log('')
    return
  }

  const config: AgenticConfig = {
    projectName: basename(targetDir),
    targetDir,
  }

  generateShared(config)
  if (selectedIds.includes('claude-code')) generateClaudeCode(config)
  if (selectedIds.includes('codex')) generateCodex(config)
  if (selectedIds.includes('cursor')) generateCursor(config)

  console.log('')
  console.log('   Agentic setup complete:')
  if (selectedIds.includes('claude-code')) {
    console.log('   ✓ Claude Code — CLAUDE.md, .claude/hooks/, .mcp.json.example')
  }
  if (selectedIds.includes('codex')) {
    console.log('   ✓ Codex — AGENTS.md enforcement rules, .codex/mcp.json.example')
  }
  if (selectedIds.includes('cursor')) {
    console.log('   ✓ Cursor — .cursor/rules/, .cursor/hooks/, .cursor/mcp.json.example')
  }
  console.log('')
}
