import path from 'node:path'
import type { GenerateWatchPlan } from './generate-watch-plan'
import type { PackageResolver } from './resolver'
import type { GeneratorResult } from './utils'
import { createResolver } from './resolver'
import * as generators from './generators'
import { getOpenApiGeneratorDependencies } from './generators/openapi'

/** Run selected generators in the same dependency order as explicit full generation. */
export async function runGenerateWatchSuite(
  quiet: boolean,
  plan?: GenerateWatchPlan,
  providedResolver?: PackageResolver,
  onOpenApiCascade?: (reason: string) => void,
): Promise<boolean> {
  if (plan?.mode === 'none') return false
  const resolver = providedResolver ?? createResolver()
  const selected = (group: GenerateWatchPlan['groups'][number]) =>
    plan?.mode !== 'incremental' || plan.groups.includes(group)
  const openApiSelected = selected('openapi')
  const openApiDependencies = openApiSelected ? undefined : getOpenApiGeneratorDependencies(resolver)
  let cascadeReason: string | undefined
  let changed = false
  const record = (result: GeneratorResult | undefined) => {
    if (result?.errors.length) throw new Error(result.errors.join('\n'))
    if (result?.filesWritten.length) changed = true
    if (openApiSelected || cascadeReason || !result?.filesWritten.length) return
    if (openApiDependencies === null) {
      cascadeReason = 'generated bytes changed but the OpenAPI dependency manifest is unavailable'
      return
    }
    for (const changedPath of result.filesWritten) {
      const absolutePath = path.resolve(changedPath)
      const dependentPath = openApiDependencies?.find((inputPath) =>
        inputPath === absolutePath || inputPath.startsWith(`${absolutePath}${path.sep}`))
      if (dependentPath) {
        cascadeReason = `generated OpenAPI dependency changed: ${dependentPath}`
        break
      }
    }
  }

  if (selected('entity-ids')) record(await generators.generateEntityIds({ resolver, quiet }))
  if (selected('registry')) {
    const results = await generators.generateModuleRegistries({
      resolver,
      quiet,
      ...(plan?.mode === 'incremental' ? { outputGroups: plan.registryOutputs } : {}),
    })
    for (const result of results) record(result)
  }
  if (selected('entities')) record(await generators.generateModuleEntities({ resolver, quiet }))
  if (selected('di')) record(await generators.generateModuleDi({ resolver, quiet }))
  if (selected('package-sources')) record(await generators.generateModulePackageSources({ resolver, quiet }))
  if (selected('web-research-adapters')) record(await generators.generateWebResearchAdapters({ resolver, quiet }))
  if (cascadeReason) {
    if (onOpenApiCascade) onOpenApiCascade(cascadeReason)
    else if (!quiet) console.log(`[generate:watch] Cascading; groups=openapi; reason=${cascadeReason}`)
  }
  if (openApiSelected || cascadeReason) record(await generators.generateOpenApi({ resolver, quiet }))
  return changed
}
