import fs from 'node:fs'
import path from 'node:path'
import { StructureKind, VariableDeclarationKind } from 'ts-morph'
import type { PackageResolver } from '../resolver'
import { MODULE_CODE_EXTENSIONS, stripModuleCodeExtension } from './scanner'
import {
  calculateChecksum,
  readChecksumRecord,
  writeChecksumRecord,
  ensureDir,
  toVar,
  logGenerationResult,
  type GeneratorResult,
  createGeneratorResult,
} from '../utils'
import {
  addAutoGeneratedComment,
  addImportSpec,
  arrayLiteral,
  createGeneratedSourceFile,
  getSourceText,
} from './ast'

export interface ModuleEntitiesOptions {
  resolver: PackageResolver
  quiet?: boolean
}

export async function generateModuleEntities(options: ModuleEntitiesOptions): Promise<GeneratorResult> {
  const { resolver, quiet = false } = options
  const result = createGeneratorResult()

  const outputDir = resolver.getOutputDir()
  const outFile = path.join(outputDir, 'entities.generated.ts')
  const checksumFile = path.join(outputDir, 'entities.generated.checksum')

  const mods = resolver.loadEnabledModules()
  const imports: Array<{ name: string; moduleSpecifier: string }> = []
  const entitySources: Array<{ importName: string; moduleId: string }> = []
  let n = 0

  for (const entry of mods) {
    const modId = entry.id
    const roots = resolver.getModulePaths(entry)
    const imp = resolver.getModuleImportBase(entry)
    const isAppModule = entry.from === '@app'

    // prefer app override data/, fallback to core data/, then legacy db/
    const appData = path.join(roots.appBase, 'data')
    const pkgData = path.join(roots.pkgBase, 'data')
    const appDb = path.join(roots.appBase, 'db')
    const pkgDb = path.join(roots.pkgBase, 'db')
    const bases = [appData, pkgData, appDb, pkgDb]
    const candidates = ['entities.override', 'entities', 'schema']

    let found: { base: string; file: string } | null = null
    for (const base of bases) {
      for (const f of candidates) {
        const p = resolveConventionFile(base, f)
        if (p) {
          found = { base, file: path.basename(p) }
          break
        }
      }
      if (found) break
    }
    if (!found) continue

    const importName = `E_${toVar(modId)}_${n++}`
    const sub = path.basename(found.base) // 'data' or 'db'
    const fromApp = found.base.startsWith(roots.appBase)
    // For @app modules, use relative path to ensure it works both in Next.js and Node.js CLI context
    // From .mercato/generated/, the relative path to src/modules/ is ../src/modules/
    let relImport: string
    if (isAppModule && fromApp) {
      // From .mercato/generated/, go up two levels (../..) to reach the app root, then into src/modules/
      relImport = `../../src/modules/${modId}/${sub}/${stripModuleCodeExtension(found.file)}`
    } else {
      const baseImport = fromApp ? imp.appBase : imp.pkgBase
      relImport = `${baseImport}/${sub}/${stripModuleCodeExtension(found.file)}`
    }
    imports.push({ name: importName, moduleSpecifier: relImport })
    entitySources.push({ importName, moduleId: modId })
  }

  const sourceFile = createGeneratedSourceFile('entities.generated.ts')
  addAutoGeneratedComment(sourceFile, 'entities')
  imports.forEach((entry) => {
    addImportSpec(sourceFile, {
      kind: StructureKind.ImportDeclaration,
      namespaceImport: entry.name,
      moduleSpecifier: entry.moduleSpecifier,
    })
  })
  sourceFile.addFunction({
    name: 'enhanceEntities',
    parameters: [
      { name: 'namespace', type: 'Record<string, unknown>' },
      { name: 'moduleId', type: 'string' },
    ],
    returnType: 'any[]',
    statements: (writer) => {
      writer.writeLine('return Object.entries(namespace)')
      writer.writeLine("  .filter(([, value]) => typeof value === 'function')")
      writer.writeLine('  .map(([exportName, value]) => {')
      writer.writeLine("    const entity = value as { entityName?: string }")
      writer.writeLine("    if (entity && typeof entity === 'function' && !Object.prototype.hasOwnProperty.call(entity, 'entityName')) {")
      writer.writeLine("      Object.defineProperty(entity, 'entityName', {")
      writer.writeLine("        value: `${moduleId}.${exportName}`,")
      writer.writeLine('        configurable: true,')
      writer.writeLine('        enumerable: false,')
      writer.writeLine('        writable: false,')
      writer.writeLine('      })')
      writer.writeLine('    }')
      writer.writeLine('    return entity')
      writer.write('  })')
    },
  })
  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
      {
        name: 'entities',
        initializer: arrayLiteral(entitySources, (writer, entry) => {
          writer.write('...enhanceEntities(')
          writer.write(entry.importName)
          writer.write(', ')
          writer.write(JSON.stringify(entry.moduleId))
          writer.write(')')
        }),
      },
    ],
  })
  const output = getSourceText(sourceFile)

  // Check if content has changed
  const newChecksum = calculateChecksum(output)
  let shouldWrite = true

  const existingRecord = readChecksumRecord(checksumFile)
  if (existingRecord && existingRecord.content === newChecksum) {
    shouldWrite = false
  }

  if (shouldWrite) {
    ensureDir(outFile)
    fs.writeFileSync(outFile, output)
    writeChecksumRecord(checksumFile, { content: newChecksum, structure: '' })
    result.filesWritten.push(outFile)
    if (!quiet) {
      logGenerationResult(path.relative(process.cwd(), outFile), true)
    }
  } else {
    result.filesUnchanged.push(outFile)
  }

  return result
}

function resolveConventionFile(baseDir: string, basename: string): string | null {
  for (const extension of MODULE_CODE_EXTENSIONS) {
    const candidate = path.join(baseDir, `${basename}${extension}`)
    if (fs.existsSync(candidate)) return candidate
  }
  return null
}
