/** @jest-environment jsdom */
jest.setTimeout(15000)

jest.mock('next/navigation', () => ({
  useRouter: () => ({ push: () => {} }),
  usePathname: () => '/',
  useSearchParams: () => new URLSearchParams(),
}))
jest.mock('remark-gfm', () => ({ __esModule: true, default: {} }))
jest.mock('../injection/InjectionSpot', () => ({
  __esModule: true,
  InjectionSpot: () => null,
  useInjectionWidgets: () => ({ widgets: [], loading: false, error: null }),
  useInjectionSpotEvents: () => ({ triggerEvent: async () => ({ ok: true }) }),
}))
jest.mock('../injection/useInjectionDataWidgets', () => ({
  __esModule: true,
  useInjectionDataWidgets: () => ({ widgets: [], isLoading: false, error: null }),
}))

import * as React from 'react'
import { act, fireEvent } from '@testing-library/react'
import { renderWithProviders } from '@open-mercato/shared/lib/testing/renderWithProviders'
import { CrudForm, type CrudField } from '../CrudForm'

const dict = {
  'ui.forms.actions.save': 'Save',
  'ui.forms.select.emptyOption': '—',
}

describe('CrudForm field-level readOnly (#3704)', () => {
  it('marks a read-only text field non-editable', async () => {
    const fields: CrudField[] = [{ id: 'label', label: 'Label', type: 'text', readOnly: true }]
    const { container } = renderWithProviders(
      <CrudForm
        title="Form"
        fields={fields}
        initialValues={{ label: 'Activity' }}
        onSubmit={() => {}}
      />,
      { dict },
    )

    const input = container.querySelector('[data-crud-field-id="label"] input') as HTMLInputElement
    expect(input).not.toBeNull()
    expect(input).toHaveAttribute('readonly')

    await act(async () => {
      fireEvent.change(input, { target: { value: 'Edited' } })
    })

    expect(input.value).toBe('Activity')
  })

  it('marks a read-only textarea non-editable', () => {
    const fields: CrudField[] = [{ id: 'description', label: 'Description', type: 'textarea', readOnly: true }]
    const { container } = renderWithProviders(
      <CrudForm
        title="Form"
        fields={fields}
        initialValues={{ description: 'Generated by code' }}
        onSubmit={() => {}}
      />,
      { dict },
    )

    const textarea = container.querySelector('[data-crud-field-id="description"] textarea') as HTMLTextAreaElement
    expect(textarea).not.toBeNull()
    expect(textarea).toHaveAttribute('readonly')
  })

  it('disables a read-only select trigger so the value cannot be changed', () => {
    const fields: CrudField[] = [
      {
        id: 'defaultEditor',
        label: 'Default Editor',
        type: 'select',
        readOnly: true,
        options: [
          { value: 'markdown', label: 'Markdown' },
          { value: 'htmlRichText', label: 'HTML Rich Text' },
        ],
      },
    ]
    const { getByRole } = renderWithProviders(
      <CrudForm
        title="Form"
        fields={fields}
        initialValues={{ defaultEditor: 'markdown' }}
        onSubmit={() => {}}
      />,
      { dict },
    )

    expect(getByRole('combobox')).toBeDisabled()
  })

  it('keeps editable fields editable when readOnly is not set', async () => {
    const fields: CrudField[] = [{ id: 'label', label: 'Label', type: 'text' }]
    const { container } = renderWithProviders(
      <CrudForm
        title="Form"
        fields={fields}
        initialValues={{ label: 'Activity' }}
        onSubmit={() => {}}
      />,
      { dict },
    )

    const input = container.querySelector('[data-crud-field-id="label"] input') as HTMLInputElement
    expect(input).not.toBeNull()
    expect(input).not.toHaveAttribute('readonly')

    await act(async () => {
      fireEvent.change(input, { target: { value: 'Edited' } })
    })

    expect(input.value).toBe('Edited')
  })
})
