import { CodeBlockWriter, IndentationText, Project, type SourceFile } from 'ts-morph'
import { writeValue, type GeneratedValue } from './writers'

let sharedProject: Project | null = null

function getProject(): Project {
  if (!sharedProject) {
    sharedProject = new Project({
      useInMemoryFileSystem: true,
      manipulationSettings: {
        indentationText: IndentationText.TwoSpaces,
        useTrailingCommas: false,
      },
    })
  }

  return sharedProject
}

export function createGeneratedSourceFile(fileName: string): SourceFile {
  const project = getProject()
  const existing = project.getSourceFile(fileName)
  if (existing) {
    project.removeSourceFile(existing)
  }

  return project.createSourceFile(fileName, '', { overwrite: true })
}

export function addAutoGeneratedComment(sourceFile: SourceFile, generator: string): void {
  sourceFile.insertText(0, `// AUTO-GENERATED by mercato generate ${generator}\n`)
}

export function renderExpressionText(value: GeneratedValue): string {
  const writer = new CodeBlockWriter({ indentNumberOfSpaces: 2 })
  writeValue(writer, value)
  return writer.toString()
}

export function getSourceText(sourceFile: SourceFile): string {
  const text = sourceFile.getFullText().replace(/\r\n/g, '\n')
  const headerMatch = text.match(/\/\/ AUTO-GENERATED by mercato generate [^\n]+\n/)
  let normalized = text

  if (headerMatch && !text.startsWith(headerMatch[0])) {
    normalized = `${headerMatch[0]}${text.replace(headerMatch[0], '')}`
  }

  return normalized.endsWith('\n') ? normalized : `${normalized}\n`
}
