import type { GeneratorPlugin } from '@open-mercato/shared/modules/generators'

export const generatorPlugins: GeneratorPlugin[] = [{
  id: 'document_generators.templates',
  conventionFile: 'document-generators.ts',
  importPrefix: 'DOCUMENT_TEMPLATES',
  configExpr: (importName: string) => `...(${importName}.templates as TemplateEntry[])`,
  outputFileName: 'document-generators.generated.ts',
  buildOutput: ({ importSection, entriesLiteral }) => `// AUTO-GENERATED by mercato generate registry
import type { TemplateEntry } from '@open-mercato/shared/modules/document-generators'
${importSection}
export const documentTemplateEntries: TemplateEntry[] = [
${entriesLiteral}
]
`,
  bootstrapRegistration: {
    entriesExportName: 'documentTemplateEntries',
    registrationImports: [
      "import { templateRegistry } from '@open-mercato/document-generators/modules/document_generators/lib/template-registry'",
    ],
    buildCall: (entriesExportName: string) => `templateRegistry.register(${entriesExportName})`,
  },
}]
