import type { GeneratorPlugin } from '@open-mercato/shared/modules/generators'

/**
 * Builds the content of the auto-generated registry file that collects module template entries.
 *
 * @param importSection - Generated import statements for each convention file
 * @param entriesLiteral - Generated array literal entries
 * @returns Source code string written to document-generators.generated.ts
 */
function buildOutput({ importSection, entriesLiteral }: { importSection: string; entriesLiteral: string }): string {
  return `// AUTO-GENERATED by mercato generate registry
import type { TemplateEntry } from '@open-mercato/shared/modules/document-generators'
${importSection ? `\n${importSection}\n` : ''}
export const documentGeneratorTemplateEntries: Array<{ entity: string; templates: TemplateEntry[] }> = [
${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]
`
}

const documentGeneratorsPlugin: GeneratorPlugin = {
  id: 'document-generators.templates',
  conventionFile: 'document-generators.ts',
  importPrefix: 'DOCUMENT_GENERATORS_TEMPLATES',
  configExpr: (importName: string, entity: string) =>
    `{ entity: '${entity}', templates: ((${importName}.default ?? ${importName}.templates ?? []) as TemplateEntry[]) }`,
  outputFileName: 'document-generators.generated.ts',
  buildOutput,
  bootstrapRegistration: {
    entriesExportName: 'documentGeneratorTemplateEntries',
    registrationImports: [
      `import { templateRegistry } from '@open-mercato/document-generators/modules/document_generators/lib/template-registry'`,
    ],
    buildCall: (name: string) =>
      `templateRegistry.register(${name}.flatMap((e) => e.templates))`,
  },
}

/** Generator plugins consumed by `mercato generate registry` to produce the template registry file. */
export const generatorPlugins: GeneratorPlugin[] = [documentGeneratorsPlugin]

export default generatorPlugins
