import type { CodeBlockWriter, SourceFile, WriterFunction } from 'ts-morph'
import {
  addAutoGeneratedComment,
  addImportSpecs,
  objectLiteral,
  createGeneratedSourceFile,
  getSourceText,
  type GeneratedImportSpec,
  type GeneratedObjectEntry,
} from '../ast'

export function renderGeneratedTsSource(options: {
  fileName: string
  imports?: GeneratedImportSpec[]
  build: (sourceFile: SourceFile) => void
  generator?: string
}): string {
  const { fileName, imports = [], build, generator = 'registry' } = options
  const sourceFile = createGeneratedSourceFile(fileName)

  addAutoGeneratedComment(sourceFile, generator)
  addImportSpecs(sourceFile, imports)
  build(sourceFile)

  return getSourceText(sourceFile)
}

export function namespaceImportSpec(name: string, moduleSpecifier: string): GeneratedImportSpec {
  return {
    namespaceImport: name,
    moduleSpecifier,
  }
}

export function defaultImportSpec(name: string, moduleSpecifier: string): GeneratedImportSpec {
  return {
    defaultImport: name,
    moduleSpecifier,
  }
}

export function sideEffectImportSpec(moduleSpecifier: string): GeneratedImportSpec {
  return {
    moduleSpecifier,
  }
}

export function namespaceMember(importName: string, memberName: string): WriterFunction {
  return (writer) => {
    writer.write(importName)
    writer.write('.')
    writer.write(memberName)
  }
}

export function parenthesizedNamespaceMember(importName: string, memberName: string): WriterFunction {
  return (writer) => {
    writer.write('(')
    namespaceMember(importName, memberName)(writer)
    writer.write(')')
  }
}

export function fallbackChain(expressions: WriterFunction[]): WriterFunction {
  return (writer) => {
    expressions.forEach((expression, index) => {
      if (index > 0) {
        writer.write(' ?? ')
      }
      expression(writer)
    })
  }
}

export function namespaceFallback(options: {
  importName: string
  members: string[]
  fallback: WriterFunction
  castType?: string
}): WriterFunction {
  return (writer) => {
    writer.write('(')
    if (options.castType) {
      writer.write('(')
    }
    fallbackChain([
      ...options.members.map((memberName) => namespaceMember(options.importName, memberName)),
      options.fallback,
    ])(writer)
    if (options.castType) {
      writer.write(') as ')
      writer.write(options.castType)
    }
    writer.write(')')
  }
}

export function emptyArray(): WriterFunction {
  return (writer) => {
    writer.write('[]')
  }
}

export function emptyObject(): WriterFunction {
  return (writer) => {
    writer.write('{}')
  }
}

export function moduleEntry(
  moduleId: string,
  entries: Array<GeneratedObjectEntry>,
): WriterFunction {
  return objectLiteral([
    { name: 'moduleId', value: moduleId },
    ...entries,
  ])
}

export function dynamicImportExpression(moduleSpecifier: string): WriterFunction {
  return (writer) => {
    writer.write('import(')
    writer.write(JSON.stringify(moduleSpecifier))
    writer.write(')')
  }
}

export function writeArrayFilter(
  writer: CodeBlockWriter,
  arrayExpression: WriterFunction,
  callbackSource: string,
): void {
  arrayExpression(writer)
  writer.write('.filter(')
  writer.write(callbackSource)
  writer.write(')')
}
