// AUTO-GENERATED by mercato generate entity-ids
// Static registry for entity fields - eliminates dynamic imports for Turbopack compatibility

export const entityFieldsRegistry: Record<string, Record<string, string>> = {
}

export function getEntityFields(slug: string): Record<string, string> | undefined {
  return entityFieldsRegistry[slug]
}
