export const features = [
  { id: 'customers.people.view', title: 'View people', module: 'customers' },
  { id: 'customers.people.manage', title: 'Manage people', module: 'customers' },
  { id: 'customers.companies.view', title: 'View companies', module: 'customers' },
  { id: 'customers.companies.manage', title: 'Manage companies', module: 'customers' },
  { id: 'customers.branches.view', title: 'View branches', module: 'customers' },
  { id: 'customers.branches.manage', title: 'Manage branches', module: 'customers' },
  { id: 'customers.deals.view', title: 'View deals', module: 'customers' },
  { id: 'customers.deals.manage', title: 'Manage deals', module: 'customers' },
  { id: 'customers.activities.view', title: 'View activities', module: 'customers' },
  { id: 'customers.activities.manage', title: 'Manage activities', module: 'customers' },
  { id: 'customers.settings.manage', title: 'Manage customer settings', module: 'customers' },
  { id: 'customers.pipelines.view', title: 'View pipelines', module: 'customers' },
  { id: 'customers.pipelines.manage', title: 'Manage pipelines', module: 'customers' },
  { id: 'customers.widgets.todos', title: 'Use customer todos widget', module: 'customers' },
  { id: 'customers.widgets.next-interactions', title: 'Use customer next interactions widget', module: 'customers' },
  { id: 'customers.widgets.new-customers', title: 'Use customer new customers widget', module: 'customers' },
  { id: 'customers.widgets.new-deals', title: 'Use customer new deals widget', module: 'customers' },
  { id: 'customers.analytics.view', title: 'View CRM analytics', module: 'customers' },
  { id: 'customers.deals.bulk', title: 'Bulk update deals', module: 'customers' },
  { id: 'customers.saved-views.manage', title: 'Manage saved views', module: 'customers' },
  { id: 'customers.emails.view', title: 'View deal emails', module: 'customers' },
  { id: 'customers.emails.send', title: 'Send emails from deals', module: 'customers' },
]

export default features
