import type { GeneratorPlugin } from '@open-mercato/shared/modules/generators'

function buildCalendarEventTypesOutput({
  importSection,
  entriesLiteral,
}: {
  importSection: string
  entriesLiteral: string
}): string {
  return `// AUTO-GENERATED by mercato generate registry
import type { CalendarEventTypeDefinition, CalendarEventTypeDefinitionOverride, NormalizedCalendarEventTypeEntry } from '@open-mercato/core/modules/customers/calendar-event-types'
${importSection ? `\n${importSection}\n` : '\n'}
type CalendarEventTypeEntryRaw = {
  moduleId: string
  sourcePath: string
  definitions: CalendarEventTypeDefinition[]
  overrides: Record<string, CalendarEventTypeDefinitionOverride | null>
}

const calendarEventTypeEntriesRaw: CalendarEventTypeEntryRaw[] = [
${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]

export const calendarEventTypeEntries: NormalizedCalendarEventTypeEntry[] = calendarEventTypeEntriesRaw.map((entry, moduleOrder) => ({
  ...entry,
  moduleOrder,
}))
`
}

const calendarEventTypesPlugin: GeneratorPlugin = {
  id: 'customers.calendar-event-types',
  conventionFile: 'calendar-event-types.ts',
  importPrefix: 'CUSTOMERS_CALENDAR_EVENT_TYPES',
  configExpr: (importName: string, moduleId: string) => {
    const definitions = moduleId === 'customers'
      ? '[]'
      : `((${importName}.default ?? ${importName}.calendarEventTypes ?? []) as CalendarEventTypeDefinition[])`
    const overrides = moduleId === 'customers'
      ? '{}'
      : `((${importName}.calendarEventTypeOverrides ?? {}) as Record<string, CalendarEventTypeDefinitionOverride | null>)`
    return `{ moduleId: '${moduleId}', sourcePath: '${moduleId}/calendar-event-types.ts', definitions: ${definitions}, overrides: ${overrides} }`
  },
  outputFileName: 'calendar-event-types.generated.ts',
  buildOutput: buildCalendarEventTypesOutput,
  bootstrapRegistration: {
    entriesExportName: 'calendarEventTypeEntries',
    registrationImports: [
      `import { registerCalendarEventTypeEntries } from '@open-mercato/core/modules/customers/calendar-event-types'`,
    ],
    buildCall: (name: string) => `registerCalendarEventTypeEntries(${name})`,
  },
}

export const generatorPlugins: GeneratorPlugin[] = [calendarEventTypesPlugin]

export default generatorPlugins
