import type { RestaurantSeed } from './types'

export const restaurantSeed: RestaurantSeed = {
  restaurant: {
    name: 'Luna Mesa',
    location: 'Madrid · Chamberí',
    serviceMode: 'Mobile-first dine-in ordering',
    currency: 'EUR',
    brandTone: 'Mediterranean bistro with fast table turnover',
  },
  tables: [
    { id: 't12', label: 'Mesa 12', zone: 'Terraza', seats: 4, qrPath: '/restaurant/table/t12' },
    { id: 't08', label: 'Mesa 8', zone: 'Salón', seats: 2, qrPath: '/restaurant/table/t08' },
    { id: 't03', label: 'Mesa 3', zone: 'Barra', seats: 2, qrPath: '/restaurant/table/t03' },
  ],
  menu: [
    {
      id: 'burger-smash',
      slug: 'smash-burger-trufa',
      name: 'Smash burger trufa',
      category: 'Principales',
      description: 'Doble carne, cheddar, cebolla caramelizada y mayo de trufa.',
      price: 14,
      prepMinutes: 11,
      tags: ['best seller', 'fast'],
      modifierGroups: [
        {
          id: 'cook',
          label: 'Punto de cocción',
          required: true,
          options: [
            { id: 'medium', label: 'Al punto', priceDelta: 0 },
            { id: 'well', label: 'Hecha', priceDelta: 0 },
          ],
        },
        {
          id: 'extras',
          label: 'Extras',
          options: [
            { id: 'bacon', label: 'Bacon ahumado', priceDelta: 1.5 },
            { id: 'egg', label: 'Huevo plancha', priceDelta: 1.2 },
          ],
        },
      ],
      recipe: [
        { ingredientId: 'beef', quantity: 180, unit: 'g' },
        { ingredientId: 'bun', quantity: 1, unit: 'unit' },
        { ingredientId: 'cheddar', quantity: 40, unit: 'g' },
        { ingredientId: 'truffle-mayo', quantity: 25, unit: 'g' },
        { ingredientId: 'onion', quantity: 30, unit: 'g' },
      ],
    },
    {
      id: 'croquetas',
      slug: 'croquetas-jamon',
      name: 'Croquetas de jamón',
      category: 'Entrantes',
      description: 'Seis croquetas cremosas con alioli cítrico.',
      price: 9,
      prepMinutes: 7,
      tags: ['shareable'],
      recipe: [
        { ingredientId: 'croqueta-mix', quantity: 180, unit: 'g' },
        { ingredientId: 'alioli', quantity: 30, unit: 'g' },
      ],
    },
    {
      id: 'salad',
      slug: 'ensalada-burrata',
      name: 'Ensalada burrata',
      category: 'Ensaladas',
      description: 'Tomate semiseco, pesto, rúcula y burrata cremosa.',
      price: 12,
      prepMinutes: 6,
      tags: ['vegetarian'],
      recipe: [
        { ingredientId: 'burrata', quantity: 1, unit: 'unit' },
        { ingredientId: 'tomato', quantity: 120, unit: 'g' },
        { ingredientId: 'pesto', quantity: 20, unit: 'g' },
        { ingredientId: 'rocket', quantity: 35, unit: 'g' },
      ],
    },
    {
      id: 'spritz',
      slug: 'aperol-spritz',
      name: 'Aperol spritz',
      category: 'Bebidas',
      description: 'Aperol, cava brut y soda con piel de naranja.',
      price: 8,
      prepMinutes: 3,
      tags: ['bar'],
      recipe: [
        { ingredientId: 'aperol', quantity: 90, unit: 'ml' },
        { ingredientId: 'cava', quantity: 120, unit: 'ml' },
        { ingredientId: 'soda', quantity: 30, unit: 'ml' },
        { ingredientId: 'orange', quantity: 1, unit: 'unit' },
      ],
    },
  ],
  ingredients: [
    { id: 'beef', name: 'Carne smash', unit: 'g', onHand: 4000, safetyStock: 1400, incoming: 2000, waste: 200, manualAdjustment: 0, supplier: 'Carnes Sierra', costPerUnit: 0.018 },
    { id: 'bun', name: 'Pan brioche', unit: 'unit', onHand: 28, safetyStock: 12, incoming: 24, waste: 1, manualAdjustment: 0, supplier: 'Panadería Norte', costPerUnit: 0.65 },
    { id: 'cheddar', name: 'Cheddar madurado', unit: 'g', onHand: 1800, safetyStock: 600, incoming: 0, waste: 50, manualAdjustment: 0, supplier: 'Quesos Alba', costPerUnit: 0.012 },
    { id: 'truffle-mayo', name: 'Mayo trufada', unit: 'g', onHand: 850, safetyStock: 250, incoming: 0, waste: 30, manualAdjustment: 0, supplier: 'Salsas Atelier', costPerUnit: 0.02 },
    { id: 'onion', name: 'Cebolla caramelizada', unit: 'g', onHand: 1300, safetyStock: 400, incoming: 0, waste: 60, manualAdjustment: 0, supplier: 'Huerta Sur', costPerUnit: 0.004 },
    { id: 'croqueta-mix', name: 'Masa croqueta jamón', unit: 'g', onHand: 2100, safetyStock: 720, incoming: 1800, waste: 80, manualAdjustment: 0, supplier: 'Obrador Central', costPerUnit: 0.01 },
    { id: 'alioli', name: 'Alioli cítrico', unit: 'g', onHand: 700, safetyStock: 180, incoming: 0, waste: 25, manualAdjustment: 0, supplier: 'Salsas Atelier', costPerUnit: 0.008 },
    { id: 'burrata', name: 'Burrata', unit: 'unit', onHand: 9, safetyStock: 4, incoming: 6, waste: 0, manualAdjustment: 0, supplier: 'Quesos Alba', costPerUnit: 2.1 },
    { id: 'tomato', name: 'Tomate semiseco', unit: 'g', onHand: 1500, safetyStock: 500, incoming: 0, waste: 40, manualAdjustment: 0, supplier: 'Huerta Sur', costPerUnit: 0.005 },
    { id: 'pesto', name: 'Pesto', unit: 'g', onHand: 600, safetyStock: 180, incoming: 0, waste: 20, manualAdjustment: 0, supplier: 'Despensa Verde', costPerUnit: 0.015 },
    { id: 'rocket', name: 'Rúcula', unit: 'g', onHand: 500, safetyStock: 120, incoming: 300, waste: 40, manualAdjustment: 0, supplier: 'Huerta Sur', costPerUnit: 0.01 },
    { id: 'aperol', name: 'Aperol', unit: 'ml', onHand: 2500, safetyStock: 600, incoming: 1500, waste: 0, manualAdjustment: 0, supplier: 'Distribuciones Sol', costPerUnit: 0.014 },
    { id: 'cava', name: 'Cava brut', unit: 'ml', onHand: 3200, safetyStock: 900, incoming: 2400, waste: 0, manualAdjustment: 0, supplier: 'Distribuciones Sol', costPerUnit: 0.009 },
    { id: 'soda', name: 'Soda', unit: 'ml', onHand: 1800, safetyStock: 500, incoming: 1200, waste: 0, manualAdjustment: 0, supplier: 'Distribuciones Sol', costPerUnit: 0.003 },
    { id: 'orange', name: 'Naranja', unit: 'unit', onHand: 22, safetyStock: 8, incoming: 20, waste: 1, manualAdjustment: 0, supplier: 'Huerta Sur', costPerUnit: 0.22 },
  ],
  orders: [
    {
      id: 'ord-1001',
      tableId: 't08',
      createdAtLabel: '19:08',
      status: 'preparing',
      paymentStatus: 'paid',
      priority: 'high',
      source: 'web-table',
      guestCount: 2,
      total: 22,
      lines: [
        { id: 'ol-1', menuItemId: 'burger-smash', itemName: 'Smash burger trufa', quantity: 1, note: 'Sin pepinillo', selectedOptionIds: ['medium'], unitPrice: 14 },
        { id: 'ol-2', menuItemId: 'spritz', itemName: 'Aperol spritz', quantity: 1, note: '', selectedOptionIds: [], unitPrice: 8 },
      ],
    },
    {
      id: 'ord-1002',
      tableId: 't03',
      createdAtLabel: '19:11',
      status: 'ready',
      paymentStatus: 'paid',
      priority: 'normal',
      source: 'web-table',
      guestCount: 2,
      total: 18,
      lines: [
        { id: 'ol-3', menuItemId: 'croquetas', itemName: 'Croquetas de jamón', quantity: 2, note: '', selectedOptionIds: [], unitPrice: 9 },
      ],
    },
  ],
  purchaseReceipts: [
    {
      id: 'po-340',
      supplier: 'Carnes Sierra',
      status: 'pending',
      reference: 'FAC-2026-340',
      entries: [
        { ingredientId: 'beef', quantity: 2000 },
        { ingredientId: 'bun', quantity: 24 },
      ],
    },
    {
      id: 'po-341',
      supplier: 'Huerta Sur',
      status: 'pending',
      reference: 'FAC-2026-341',
      entries: [
        { ingredientId: 'rocket', quantity: 300 },
        { ingredientId: 'orange', quantity: 20 },
      ],
    },
  ],
}
