import type { LegacyColumnDef as ColumnDef } from '@tanstack/react-table/legacy'
import type { TranslateFn } from '@open-mercato/shared/lib/i18n/context'
import { formatDateTime } from '@open-mercato/shared/lib/time'
import type { DocumentHistoryItem } from '../../../../hooks/history/useDocumentHistory'

export function buildHistoryListTableColumns(t: TranslateFn): ColumnDef<DocumentHistoryItem>[] {
  return [
    { accessorKey: 'resourceLabel', header: t('document_generators.history.resource', 'Resource'), meta: { truncate: true } },
    { accessorKey: 'templateLabel', header: t('document_generators.history.template', 'Template') },
    {
      accessorKey: 'generatedAt',
      header: t('document_generators.history.generatedAt', 'Date'),
      cell: ({ getValue }) => formatDateTime(String(getValue() ?? '')) ?? '—',
      meta: { maxWidth: 190 },
    },
    {
      accessorKey: 'format',
      header: t('document_generators.history.format', 'Format'),
      cell: ({ getValue }) => String(getValue() ?? '').toUpperCase(),
      meta: { maxWidth: 100 },
    },
    { accessorKey: 'generatedBy', header: t('document_generators.history.generatedBy', 'Generated by'), meta: { maxWidth: 260, truncate: true } },
    { accessorKey: 'resourceKind', header: t('document_generators.history.resourceKind', 'Resource type'), enableSorting: false, meta: { maxWidth: 160, truncate: true } },
    { accessorKey: 'resourceId', header: t('document_generators.history.resourceId', 'Resource ID'), enableSorting: false, meta: { maxWidth: 220, truncate: true } },
    { accessorKey: 'templateId', header: t('document_generators.history.templateId', 'Template ID'), enableSorting: false, meta: { maxWidth: 180, truncate: true } },
    { accessorKey: 'id', header: t('document_generators.history.id', 'History ID'), enableSorting: false, meta: { maxWidth: 220, truncate: true } },
  ]
}
