#!/usr/bin/env tsx
import fs from 'node:fs'
import path from 'node:path'
import { loadEnabledModules, moduleFsRoots, moduleImportBase } from './shared/modules-config'
import { getModulesDir, ensureModulesDir } from './shared/generated-paths'

function toVar(s: string) {
  return s.replace(/[^a-zA-Z0-9_]/g, '_')
}

function toSnake(s: string) {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/\W+/g, '_').replace(/_{2,}/g, '_').replace(/^_+|_+$/g, '').toLowerCase()
}

async function generateModuleExports() {
  ensureModulesDir()

  const entries = loadEnabledModules()
  const modulesDir = getModulesDir()

  for (const entry of entries) {
    const modId = entry.id
    const roots = moduleFsRoots(entry)
    const imps = moduleImportBase(entry)

    // Locate entities definition file (prefer app override)
    const appData = path.join(roots.appBase, 'data')
    const pkgData = path.join(roots.pkgBase, 'data')
    const appDb = path.join(roots.appBase, 'db')
    const pkgDb = path.join(roots.pkgBase, 'db')
    const bases = [appData, pkgData, appDb, pkgDb]
    const candidates = ['entities.override.ts', 'entities.ts', 'schema.ts']
    let importPath: string | null = null
    let filePath: string | null = null

    for (const base of bases) {
      for (const f of candidates) {
        const p = path.join(base, f)
        if (fs.existsSync(p)) {
          const fromApp = base.startsWith(roots.appBase)
          const sub = path.basename(base)
          importPath = `${fromApp ? imps.appBase : imps.pkgBase}/${sub}/${f.replace(/\.ts$/, '')}`
          filePath = p
          break
        }
      }
      if (importPath) break
    }

    if (!importPath || !filePath) continue

    // Dynamically import to get entity names
    try {
      const mod = await import(importPath)
      const entityNames = Object.keys(mod)
        .filter((k) => typeof mod[k] === 'function')
        .filter((k) => k !== 'default')

      if (entityNames.length === 0) continue

      // Create module directory
      const moduleDir = path.join(modulesDir, modId)
      fs.mkdirSync(moduleDir, { recursive: true })

      const content = `// AUTO-GENERATED by scripts/generate-module-exports.ts
// Re-exports for module: ${modId}
// Usage: import { ${entityNames[0]} } from '@open-mercato/generated/modules/${modId}/entities'
export {
  ${entityNames.join(',\n  ')}
} from '../entities.generated'
`
      const outFile = path.join(moduleDir, 'entities.ts')
      fs.writeFileSync(outFile, content)
      console.log(`✅ Generated ${path.relative(process.cwd(), outFile)}`)
    } catch (err) {
      console.warn(`⚠️ Failed to process module ${modId}:`, (err as Error).message)
    }
  }
}

generateModuleExports().catch((e) => {
  console.error('Failed to generate module exports:', e)
  process.exit(1)
})
