import { z } from 'zod'
import { buildOpenApiDocument } from '../generator'
import type { Module } from '../../../modules/registry'
import type { OpenApiMethodDoc } from '../types'

const errorSchema = z.object({ error: z.string(), code: z.string() })

function makeModule(path: string, methodDoc: OpenApiMethodDoc): Module {
  return {
    id: 'example',
    apis: [
      {
        path,
        metadata: { GET: { requireAuth: true, requireFeatures: ['example.records.view'] } },
        handlers: { GET: async () => new Response(null) },
        docs: { tag: 'Example', methods: { GET: methodDoc } },
      },
    ],
  } as unknown as Module
}

function getOperation(path: string, methodDoc: OpenApiMethodDoc): Record<string, any> {
  const doc = buildOpenApiDocument([makeModule(path, methodDoc)])
  return doc.paths[path]?.get as Record<string, any>
}

describe('buildResponses precedence between declared and inferred responses', () => {
  it('keeps a 403 declared through responses instead of the requireFeatures default', () => {
    const operation = getOperation('/example/records', {
      responses: [
        { status: 200, description: 'Records', schema: z.object({ items: z.array(z.string()) }) },
        { status: 403, description: 'Record is outside the active scope', schema: errorSchema },
      ],
    })

    expect(operation.responses['403'].description).toBe('Record is outside the active scope')
    expect(operation.responses['403']['x-autoGenerated']).toBeUndefined()
    expect(operation.responses['403'].content['application/json'].schema.properties.code).toBeDefined()
  })

  it('keeps a 403 declared through errors instead of the requireFeatures default', () => {
    const operation = getOperation('/example/records', {
      responses: [{ status: 200, description: 'Records' }],
      errors: [{ status: 403, description: 'Record is outside the active scope', schema: errorSchema }],
    })

    expect(operation.responses['403'].description).toBe('Record is outside the active scope')
    expect(operation.responses['403']['x-autoGenerated']).toBeUndefined()
    expect(operation.responses['403'].content['application/json'].schema.properties.code).toBeDefined()
  })

  it('keeps a 401 declared through errors instead of the requireAuth default', () => {
    const operation = getOperation('/example/records', {
      responses: [{ status: 200, description: 'Records' }],
      errors: [{ status: 401, description: 'Session token expired', schema: errorSchema }],
    })

    expect(operation.responses['401'].description).toBe('Session token expired')
    expect(operation.responses['401']['x-autoGenerated']).toBeUndefined()
  })

  it('keeps a 401 declared through responses instead of the requireAuth default', () => {
    const operation = getOperation('/example/records', {
      responses: [
        { status: 200, description: 'Records' },
        { status: 401, description: 'Session token expired', schema: errorSchema },
      ],
    })

    expect(operation.responses['401'].description).toBe('Session token expired')
    expect(operation.responses['401']['x-autoGenerated']).toBeUndefined()
  })

  it('emits both inferred entries when the route documents neither status', () => {
    const operation = getOperation('/example/records', {
      responses: [{ status: 200, description: 'Records' }],
      errors: [{ status: 404, description: 'Not found', schema: errorSchema }],
    })

    expect(operation.responses['401'].description).toBe('Unauthorized')
    expect(operation.responses['401']['x-autoGenerated']).toBe(true)
    expect(operation.responses['403'].description).toBe('Forbidden – missing required features')
    expect(operation.responses['403']['x-autoGenerated']).toBe(true)
    expect(operation.responses['404'].description).toBe('Not found')
    expect(operation.responses['404']['x-autoGenerated']).toBeUndefined()
  })

  it('mixes a declared 403 with the inferred 401 on the same operation', () => {
    const operation = getOperation('/example/records', {
      responses: [{ status: 200, description: 'Records' }],
      errors: [{ status: 403, description: 'Record is outside the active scope', schema: errorSchema }],
    })

    expect(operation.responses['403']['x-autoGenerated']).toBeUndefined()
    expect(operation.responses['401']['x-autoGenerated']).toBe(true)
  })

  it('still synthesises the success response when the route declares only errors', () => {
    const operation = getOperation('/example/records', {
      errors: [{ status: 403, description: 'Record is outside the active scope', schema: errorSchema }],
    })

    expect(operation.responses['200'].description).toBe('Success response')
    expect(operation.responses['403'].description).toBe('Record is outside the active scope')
  })
})
