import type { GeneratorPlugin } from '@open-mercato/shared/modules/generators'

const accessPlugin: GeneratorPlugin = {
  id: 'attachments.access-resolvers',
  conventionFile: 'data/attachment-access.ts',
  importPrefix: 'ATTACHMENT_ACCESS',
  configExpr: (importName, moduleId) =>
    `{ moduleId: '${moduleId}', resolvers: (${importName}.attachmentAccessResolvers ?? []), protectedTargets: (${importName}.protectedAttachmentTargets ?? []) }`,
  outputFileName: 'attachment-access.generated.ts',
  buildOutput: ({ importSection, entriesLiteral }) => `// AUTO-GENERATED by mercato generate registry
import type { AttachmentAccessResolverEntry } from '@open-mercato/core/modules/attachments'
${importSection}

export const attachmentAccessEntries: AttachmentAccessResolverEntry[] = [
${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]
`,
  bootstrapRegistration: {
    entriesExportName: 'attachmentAccessEntries',
    registrationImports: [
      "import { registerAttachmentAccessResolvers } from '@open-mercato/core/modules/attachments/lib/access-registry'",
    ],
    buildCall: (entries) => `registerAttachmentAccessResolvers(${entries})`,
  },
}

export const generatorPlugins: GeneratorPlugin[] = [accessPlugin]
export default generatorPlugins
