// Auto-registered field components loaded at runtime.
// This file can be regenerated by module generators. Keep imports side-effectful.
import '@open-mercato/core/modules/attachments/fields/attachment'

export function loadAll() {
  // No-op: imports above perform registration via side effects
}

