import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "Introduction",
      collapsible: false,
      items: ["introduction/overview", "introduction/use-cases"],
    },
    {
      type: "category",
      label: "Installation",
      items: ["installation/prerequisites", "installation/setup"],
    },
    {
      type: "category",
      label: "User Guide",
      items: [
        "user-guide/overview",
        "user-guide/login",
        "user-guide/users-and-roles",
        "user-guide/api-keys",
        "user-guide/feature-toggles",
        "user-guide/custom-fieldsets",
        "user-guide/encryption",
        "user-guide/user-custom-fields",
        "user-guide/dictionaries",
        "user-guide/currencies",
        "user-guide/user-entities",
        "user-guide/system-status",
        "user-guide/products-and-sales-channels",
        "user-guide/cache-management",
        "user-guide/taxes",
        "user-guide/search",
        "user-guide/perspectives-and-sidebar",
        "user-guide/organizations",
        {
          type: "category",
          label: "Sales",
          items: [
            "user-guide/sales/orders-and-quotes",
            "user-guide/sales/create-sales-document",
            "user-guide/sales/edit-order-quote",
            "user-guide/sales/payments",
            "user-guide/sales/shipments",
            "user-guide/sales/adjustments",
            "user-guide/sales/order-items",
            "user-guide/sales/sales-settings",
          ],
        },
        {
          type: "category",
          label: "Customers",
          items: [
            "user-guide/customers",
            "user-guide/customers/people",
            "user-guide/customers/companies",
            "user-guide/customers/deals",
          ],
        },
        {
          type: "category",
          label: "Business Rules",
          items: [
            "user-guide/business-rules/index",
            "user-guide/business-rules/creating-rules",
            "user-guide/business-rules/rule-types",
            "user-guide/business-rules/conditions",
            "user-guide/business-rules/actions",
            "user-guide/business-rules/rule-sets",
            "user-guide/business-rules/execution-logs",
          ],
        },
        {
          type: "category",
          label: "Workflows",
          items: [
            "user-guide/workflows/index",
            "user-guide/workflows/creating-workflows",
            "user-guide/workflows/step-types",
            "user-guide/workflows/activities",
            "user-guide/workflows/transitions",
            "user-guide/workflows/signals",
            "user-guide/workflows/user-tasks",
            "user-guide/workflows/monitoring",
          ],
        },
        "user-guide/audit-logs",
      ],
    },
    {
      type: "category",
      label: "Architecture",
      items: ["architecture/system-overview", "architecture/data-encryption"],
    },
    {
      type: "category",
      label: "Domeny",
      items: [
        "domains/overview",
        {
          type: "category",
          label: "Źródła wspólne",
          items: [
            "domains/_sources/overview",
            {
              type: "category",
              label: "PL",
              items: [
                "domains/_sources/pl/akty-prawne/index",
                "domains/_sources/pl/akty-prawne/pzp",
                "domains/_sources/pl/akty-prawne/zasob-archiwalny",
                "domains/_sources/pl/instytucje/index",
                "domains/_sources/pl/instytucje/kio",
                "domains/_sources/pl/wytyczne/index",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Prawo",
          items: [
            "domains/prawo/overview",
            {
              type: "category",
              label: "Administracja publiczna",
              items: [
                "domains/prawo/administracja-publiczna/index",
                "domains/prawo/administracja-publiczna/sources",
                "domains/prawo/administracja-publiczna/glossary",
                "domains/prawo/administracja-publiczna/actors",
                "domains/prawo/administracja-publiczna/processes",
                {
                  type: "category",
                  label: "Wymagania",
                  items: [
                    "domains/prawo/administracja-publiczna/requirements/business",
                    "domains/prawo/administracja-publiczna/requirements/legal",
                    "domains/prawo/administracja-publiczna/requirements/evidence",
                    "domains/prawo/administracja-publiczna/requirements/data",
                    "domains/prawo/administracja-publiczna/requirements/nonfunctional",
                    "domains/prawo/administracja-publiczna/requirements/rbac",
                  ],
                },
                {
                  type: "category",
                  label: "Mapowanie",
                  items: [
                    "domains/prawo/administracja-publiczna/mapping/open-mercato",
                    "domains/prawo/administracja-publiczna/mapping/module-hypotheses",
                    "domains/prawo/administracja-publiczna/mapping/coverage",
                    "domains/prawo/administracja-publiczna/mapping/gaps",
                    "domains/prawo/administracja-publiczna/mapping/integration-points",
                    {
                      type: "category",
                      label: "OpenMercato ↔ EZD (kancelaryjno-archiwalne)",
                      items: [
                        "domains/prawo/administracja-publiczna/mapping/openmercato-ezd/index",
                        "domains/prawo/administracja-publiczna/mapping/openmercato-ezd/scope-mvp",
                        "domains/prawo/administracja-publiczna/mapping/openmercato-ezd/glossary-dev",
                        "domains/prawo/administracja-publiczna/mapping/openmercato-ezd/conceptual-model",
                        "domains/prawo/administracja-publiczna/mapping/openmercato-ezd/entity-map",
                        "domains/prawo/administracja-publiczna/mapping/openmercato-ezd/api-map",
                        "domains/prawo/administracja-publiczna/mapping/openmercato-ezd/data-dictionary",
                        "domains/prawo/administracja-publiczna/mapping/openmercato-ezd/examples-archival-packages",
                        "domains/prawo/administracja-publiczna/mapping/openmercato-ezd/decisions",
                      ],
                    },
                  ],
                },
                {
                  type: "category",
                  label: "Obszary",
                  items: [
                    {
                      type: "category",
                      label: "Archiwalno-kancelaryjne",
                      items: [
                        "domains/prawo/administracja-publiczna/obszary/archiwalno-kancelaryjne/overview",
                        "domains/prawo/administracja-publiczna/obszary/archiwalno-kancelaryjne/sources",
                        "domains/prawo/administracja-publiczna/obszary/archiwalno-kancelaryjne/requirements",
                        "domains/prawo/administracja-publiczna/obszary/archiwalno-kancelaryjne/jrwa",
                        "domains/prawo/administracja-publiczna/obszary/archiwalno-kancelaryjne/retention",
                        "domains/prawo/administracja-publiczna/obszary/archiwalno-kancelaryjne/checklist",
                        "domains/prawo/administracja-publiczna/obszary/archiwalno-kancelaryjne/obiekty-i-czynnosci",
                        "domains/prawo/administracja-publiczna/obszary/archiwalno-kancelaryjne/plan-obiektow-i-pol",
                        {
                          type: "category",
                          label: "Obiekty biznesowe",
                          items: [
                            "domains/prawo/administracja-publiczna/obszary/archiwalno-kancelaryjne/obiekty/index",
                            "domains/prawo/administracja-publiczna/obszary/archiwalno-kancelaryjne/obiekty/przesylka-wplywajaca",
                            "domains/prawo/administracja-publiczna/obszary/archiwalno-kancelaryjne/obiekty/sprawa-koszulka",
                          ],
                        },
                        {
                          type: "category",
                          label: "Czynności / zdarzenia",
                          items: [
                            "domains/prawo/administracja-publiczna/obszary/archiwalno-kancelaryjne/czynnosci/index",
                            "domains/prawo/administracja-publiczna/obszary/archiwalno-kancelaryjne/czynnosci/rejestracja-przesylki-wplywajacej",
                            "domains/prawo/administracja-publiczna/obszary/archiwalno-kancelaryjne/czynnosci/zakladanie-sprawy-i-nadanie-znaku-sprawy",
                          ],
                        },
                      ],
                    },
                    {
                      type: "category",
                      label: "KIO / PZP",
                      items: [
                        "domains/prawo/administracja-publiczna/obszary/kio-pzp/overview",
                        "domains/prawo/administracja-publiczna/obszary/kio-pzp/sources",
                        "domains/prawo/administracja-publiczna/obszary/kio-pzp/requirements",
                        "domains/prawo/administracja-publiczna/obszary/kio-pzp/timeline",
                        "domains/prawo/administracja-publiczna/obszary/kio-pzp/evidence-pack",
                      ],
                    },
                  ],
                },
                "domains/prawo/administracja-publiczna/open-questions",
                "domains/prawo/administracja-publiczna/decisions",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "REST API",
      items: [
        "api/overview",
        {
          type: "category",
          label: "Module Guides",
          items: [
            "api/auth",
            "api/directory",
            "api/dashboards",
            "api/customers",
            "api/entities",
            "api/attachments",
            "api/vector",
            "api/feature-toggles",
            {
              type: "category",
              label: "Business Rules",
              items: [
                "api/business-rules",
                "api/business-rules/rules",
                "api/business-rules/execute",
                "api/business-rules/logs",
                "api/business-rules/sets",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "CLI",
      items: [
        "cli/overview",
        "cli/api-keys",
        {
          type: "category",
          label: "Bootstrap & Database",
          items: [
            "cli/init",
            "cli/db-generate",
            "cli/db-migrate",
            "cli/db-greenfield",
          ],
        },
        {
          type: "category",
          label: "Auth Module",
          items: [
            "cli/auth-seed-roles",
            "cli/auth-setup",
            "cli/auth-add-user",
            "cli/auth-set-password",
            "cli/auth-list-orgs",
            "cli/auth-list-users",
            "cli/auth-list-tenants",
          ],
        },
        {
          type: "category",
          label: "Feature Toggles Module",
          items: [
            "cli/feature-toggles-toggle-create",
            "cli/feature-toggles-toggle-update",
            "cli/feature-toggles-toggle-delete",
            "cli/feature-toggles-override-set",
            "cli/feature-toggles-seed-defaults",
          ],
        },
        {
          type: "category",
          label: "Example Module",
          items: ["cli/example-seed-todos", "cli/example-hello"],
        },
        {
          type: "category",
          label: "Entities",
          items: ["cli/entities-install"],
        },
      ],
    },
    {
      type: "category",
      label: "Customization Tutorials",
      items: [
        "customization/build-first-app",
        "customization/create-first-module",
        "customization/create-inventory-data",
        "customization/create-inventory-api",
        "customization/list-inventory",
        "customization/inventory-crud-forms",
        "customization/custom-fields-overview",
      ],
    },
    {
      type: "category",
      label: "Framework Reference",
      items: [
        "framework/ioc/container",
        {
          type: "category",
          label: "Modules",
          items: [
            "framework/modules/overview",
            "framework/modules/routes-and-pages",
            "framework/modules/currencies",
            "framework/modules/sales-providers",
            "framework/modules/sales-calculations",
          ],
        },
        "framework/commands/overview",
        {
          type: "category",
          label: "Database & Entities",
          items: [
            "framework/database/entities",
            "framework/database/data-extensibility",
            "framework/database/query-engine",
            "framework/database/hybrid-query-engine",
            "framework/database/query-index",
            "framework/database/hybrid-search",
          ],
        },
        "framework/custom-entities/overview",
        {
          type: "category",
          label: "Admin UI",
          items: [
            "framework/admin-ui/data-grids",
            "framework/admin-ui/crud-form",
            "framework/admin-ui/field-registry",
            "framework/admin-ui/custom-field-validation",
            "framework/widget-injection",
            "framework/admin-ui/perspectives"
          ],
        },
        {
          type: "category",
          label: "Dashboard",
          items: ["framework/dashboard/widgets-overview"],
        },
        {
          type: "category",
          label: "API Routes",
          items: [
            "framework/api/api-development-guide",
            "framework/api/crud-factory",
            "framework/api/building-api-modules",
            "framework/api/extending-api",
          ],
        },
        {
          type: "category",
          label: "Events & Queue",
          items: [
            "framework/events/overview",
            "framework/events/queue-workers",
          ],
        },
        "framework/pricing-tax-overrides",
        "framework/rbac/overview",
        "framework/feature-toggles/overview",
        {
          type: "category",
          label: "Runtime",
          items: [
            "framework/runtime/data-engine",
            "framework/runtime/request-lifecycle",
          ],
        },
        {
          type: "category",
          label: "Business Rules",
          items: [
            "framework/business-rules/architecture",
            "framework/business-rules/services",
            "framework/business-rules/extending",
          ],
        },
        {
          type: "category",
          label: "Workflows",
          items: [
            "framework/workflows/index",
            "framework/workflows/architecture",
            "framework/workflows/services",
            "framework/workflows/extending",
            "framework/workflows/testing",
          ],
        },
        {
          type: "category",
          label: "Operations",
          items: [
            "framework/operations/system-status",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Hands-on Tutorials",
      items: [
        "tutorials/first-app",
        "tutorials/building-todo-module",
        "tutorials/authoring-first-module",
        "tutorials/api-data-fetching",
        "tutorials/testing",
        {
          type: "category",
          label: "Business Rules",
          items: ["tutorials/business-rules/material-availability"],
        },
      ],
    },
    {
      type: "category",
      label: "Appendix",
      items: [
        "architecture/glossary",
        "architecture/future-roadmap",
        "appendix/troubleshooting",
      ],
    },
  ],
};

export default sidebars;
