export const entities = [
  {
    id: 'wms:warehouse',
    label: 'Warehouse',
    description: 'Physical warehouse definition used by the WMS module.',
    labelField: 'name',
    showInSidebar: false,
    defaultEditor: false,
    fields: [],
  },
  {
    id: 'wms:warehouse_zone',
    label: 'Warehouse Zone',
    description: 'Logical zone inside a warehouse.',
    labelField: 'name',
    showInSidebar: false,
    defaultEditor: false,
    fields: [],
  },
  {
    id: 'wms:warehouse_location',
    label: 'Warehouse Location',
    description: 'Physical location or bin inside a warehouse.',
    labelField: 'code',
    showInSidebar: false,
    defaultEditor: false,
    fields: [],
  },
  {
    id: 'wms:product_inventory_profile',
    label: 'Product Inventory Profile',
    description: 'Variant-level inventory behavior configuration.',
    labelField: 'catalogVariantId',
    showInSidebar: false,
    defaultEditor: false,
    fields: [],
  },
  {
    id: 'wms:inventory_lot',
    label: 'Inventory Lot',
    description: 'Tracked lot or batch for traceable stock.',
    labelField: 'lotNumber',
    showInSidebar: false,
    defaultEditor: false,
    fields: [],
  },
  {
    id: 'wms:inventory_balance',
    label: 'Inventory Balance',
    description: 'Current stock bucket balance at location level.',
    labelField: 'catalogVariantId',
    showInSidebar: false,
    defaultEditor: false,
    fields: [],
  },
  {
    id: 'wms:inventory_reservation',
    label: 'Inventory Reservation',
    description: 'Reserved stock allocation for a downstream demand source.',
    labelField: 'sourceId',
    showInSidebar: false,
    defaultEditor: false,
    fields: [],
  },
  {
    id: 'wms:inventory_movement',
    label: 'Inventory Movement',
    description: 'Append-only audit ledger entry for inventory state changes.',
    labelField: 'referenceId',
    showInSidebar: false,
    defaultEditor: false,
    fields: [],
  },
  {
    id: 'wms:asn',
    label: 'ASN',
    description: 'Advanced shipping notice for structured inbound receiving.',
    labelField: 'referenceNumber',
    showInSidebar: false,
    defaultEditor: false,
    fields: [],
  },
  {
    id: 'wms:receiving_line',
    label: 'Receiving Line',
    description: 'Expected/received line against an ASN with QC outcome.',
    labelField: 'catalogVariantId',
    showInSidebar: false,
    defaultEditor: false,
    fields: [],
  },
  {
    id: 'wms:putaway_task',
    label: 'Putaway Task',
    description: 'Directed putaway task moving accepted stock from staging into storage.',
    labelField: 'catalogVariantId',
    showInSidebar: false,
    defaultEditor: false,
    fields: [],
  },
]

export default entities
