'use client'

import * as React from 'react'
import type { LegacyColumnDef as ColumnDef } from '@tanstack/react-table/legacy'
import { DataTable } from '@open-mercato/ui/backend/DataTable'
import { apiCall } from '@open-mercato/ui/backend/utils/apiCall'
import { useT } from '@open-mercato/shared/lib/i18n/context'
import { formatDateTime } from '@open-mercato/shared/lib/time'

interface HistoryItem {
  id: string
  resourceKind: string
  resourceId: string
  resourceLabel: string
  templateId: string
  templateLabel: string
  format: string
  generatedBy: string
  generatedAt: string
}

interface DocumentsResponse {
  items: HistoryItem[]
  total: number
  page: number
  pageSize: number
}

/** Generation history — the documents persisted by POST /generate (Phase 5). */
export function HistoryList() {
  const t = useT()
  const [items, setItems] = React.useState<HistoryItem[]>([])
  const [page, setPage] = React.useState(1)
  const [total, setTotal] = React.useState(0)
  const [loading, setLoading] = React.useState(true)
  const [error, setError] = React.useState<string | null>(null)
  const pageSize = 20

  React.useEffect(() => {
    let cancelled = false
    setLoading(true)
    setError(null)

    const params = new URLSearchParams({ page: String(page), pageSize: String(pageSize) })
    apiCall<DocumentsResponse>(`/api/document-generators/documents?${params.toString()}`, { method: 'GET' })
      .then(({ ok, result }) => {
        if (!ok || !result) throw new Error('[internal] Failed to load generation history')
        if (cancelled) return
        setItems(result.items)
        setTotal(result.total)
      })
      .catch(() => {
        if (!cancelled) {
          setError(t('document_generators.history.error', 'Failed to load generation history.'))
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })

    return () => {
      cancelled = true
    }
  }, [page, t])

  const columns = React.useMemo<ColumnDef<HistoryItem>[]>(() => [
    { accessorKey: 'id', header: t('document_generators.history.id', 'History ID'), meta: { maxWidth: 220, truncate: true } },
    { accessorKey: 'resourceLabel', header: t('document_generators.history.resource', 'Resource'), meta: { truncate: true } },
    { accessorKey: 'resourceKind', header: t('document_generators.history.resourceKind', 'Resource type'), meta: { maxWidth: 160, truncate: true } },
    { accessorKey: 'resourceId', header: t('document_generators.history.resourceId', 'Resource ID'), meta: { maxWidth: 220, truncate: true } },
    { accessorKey: 'templateLabel', header: t('document_generators.history.template', 'Template') },
    { accessorKey: 'templateId', header: t('document_generators.history.templateId', 'Template ID'), meta: { maxWidth: 180, truncate: true } },
    {
      accessorKey: 'format',
      header: t('document_generators.history.format', 'Format'),
      cell: ({ getValue }) => String(getValue() ?? '').toUpperCase(),
      meta: { maxWidth: 100 },
    },
    { accessorKey: 'generatedBy', header: t('document_generators.history.generatedBy', 'Generated by'), meta: { maxWidth: 260, truncate: true } },
    {
      accessorKey: 'generatedAt',
      header: t('document_generators.history.generatedAt', 'Date'),
      cell: ({ getValue }) => formatDateTime(String(getValue() ?? '')) ?? '—',
      meta: { maxWidth: 190 },
    },
  ], [t])

  const totalPages = Math.max(1, Math.ceil(total / pageSize))

  return (
    <DataTable
      columns={columns}
      data={items}
      isLoading={loading}
      error={error}
      emptyState={t('document_generators.history.empty', 'No documents have been generated yet.')}
      pagination={{ page, pageSize, total, totalPages, onPageChange: setPage }}
      disableRowClick
    />
  )
}
