'use client'

import * as React from 'react'
import type { LegacyColumnDef as ColumnDef } from '@tanstack/react-table/legacy'
import { DataTable } from '@open-mercato/ui/backend/DataTable'
import { apiCall } from '@open-mercato/ui/backend/utils/apiCall'
import { useT } from '@open-mercato/shared/lib/i18n/context'
import { formatDateTime } from '@open-mercato/shared/lib/time'

interface HistoryItem {
  id: string
  resourceKind: string
  resourceId: string
  resourceLabel: string
  templateId: string
  templateLabel: string
  format: string
  generatedBy: string
  generatedAt: string
}

interface DocumentsResponse {
  items: HistoryItem[]
  total: number
  page: number
  pageSize: number
}

/** Generation history — the documents persisted by POST /generate (Phase 5). */
export function HistoryList() {
  const t = useT()
  const [items, setItems] = React.useState<HistoryItem[]>([])
  const [loading, setLoading] = React.useState(true)
  const [error, setError] = React.useState<string | null>(null)

  React.useEffect(() => {
    apiCall<DocumentsResponse>('/api/document-generators/documents?page=1&pageSize=20', { method: 'GET' })
      .then(({ ok, result }) => {
        if (!ok || !result) throw new Error('Failed to load generation history')
        setItems(result.items)
      })
      .catch(() => setError(t('document_generators.history.error', 'Failed to load generation history.')))
      .finally(() => setLoading(false))
  }, [])

  const columns: ColumnDef<HistoryItem>[] = [
    { accessorKey: 'id', header: t('document_generators.history.id', 'History ID'), meta: { maxWidth: 220, truncate: true } },
    { accessorKey: 'resourceLabel', header: t('document_generators.history.resource', 'Resource'), meta: { truncate: true } },
    { accessorKey: 'resourceKind', header: t('document_generators.history.resourceKind', 'Resource type'), meta: { maxWidth: 160, truncate: true } },
    { accessorKey: 'resourceId', header: t('document_generators.history.resourceId', 'Resource ID'), meta: { maxWidth: 220, truncate: true } },
    { accessorKey: 'templateLabel', header: t('document_generators.history.template', 'Template') },
    { accessorKey: 'templateId', header: t('document_generators.history.templateId', 'Template ID'), meta: { maxWidth: 180, truncate: true } },
    {
      accessorKey: 'format',
      header: t('document_generators.history.format', 'Format'),
      cell: ({ getValue }) => String(getValue() ?? '').toUpperCase(),
      meta: { maxWidth: 100 },
    },
    { accessorKey: 'generatedBy', header: t('document_generators.history.generatedBy', 'Generated by'), meta: { maxWidth: 260, truncate: true } },
    {
      accessorKey: 'generatedAt',
      header: t('document_generators.history.generatedAt', 'Date'),
      cell: ({ getValue }) => formatDateTime(String(getValue() ?? '')) ?? '—',
      meta: { maxWidth: 190 },
    },
  ]

  return (
    <section>
      <h2 className="mb-4 text-base font-semibold">{t('document_generators.history.title', 'Generation history')}</h2>
      {!loading && !error && items.length === 0 ? (
        <p className="text-sm text-muted-foreground">
          {t('document_generators.history.empty', 'No documents have been generated yet.')}
        </p>
      ) : (
        <DataTable columns={columns} data={items} isLoading={loading} error={error} disableRowClick />
      )}
    </section>
  )
}
