'use client'

import * as React from 'react'
import type { SortingState } from '@tanstack/react-table'
import { useT, type TranslateFn } from '@open-mercato/shared/lib/i18n/context'
import type { FilterBarProps, FilterDef, FilterValues } from '@open-mercato/ui/backend/FilterBar'
import type { DocumentHistoryQuery } from './useDocumentHistory'

const DEFAULT_SORTING: SortingState = [{ id: 'generatedAt', desc: true }]
const HISTORY_SORT_FIELDS: Record<string, DocumentHistoryQuery['sort']> = {
  resourceLabel: 'resource_label',
  templateLabel: 'template_label',
  format: 'format',
  generatedBy: 'generated_by',
  generatedAt: 'generated_at',
}

export function buildDocumentHistoryFilterDefinitions(t: TranslateFn): FilterDef[] {
  return [
    {
      id: 'templateId',
      type: 'text',
      label: t('document_generators.history.filters.template', 'Template ID'),
      placeholder: t('document_generators.history.filters.templatePlaceholder', 'Enter a template ID'),
    },
    {
      id: 'generatedBy',
      type: 'text',
      label: t('document_generators.history.filters.generatedBy', 'Generated by user ID'),
      placeholder: t('document_generators.history.filters.generatedByPlaceholder', 'Enter a user ID'),
    },
    {
      id: 'generatedAt',
      type: 'dateRange',
      label: t('document_generators.history.filters.generatedAt', 'Generation date'),
    },
  ]
}

function dateBoundary(value: unknown, endOfDay: boolean): string | undefined {
  if (typeof value !== 'string' || !value) return undefined
  const date = new Date(`${value}T00:00:00`)
  if (Number.isNaN(date.getTime())) return undefined
  if (endOfDay) date.setHours(23, 59, 59, 999)
  return date.toISOString()
}

export function buildDocumentHistoryQuery(
  values: FilterValues,
  sorting: SortingState,
  page: number,
  pageSize: number,
): DocumentHistoryQuery {
  const generatedAt = values.generatedAt && typeof values.generatedAt === 'object'
    ? values.generatedAt as { from?: unknown; to?: unknown }
    : {}
  const activeSort = sorting[0] ?? DEFAULT_SORTING[0]
  return {
    page,
    pageSize,
    templateId: typeof values.templateId === 'string' && values.templateId.trim()
      ? values.templateId.trim()
      : undefined,
    generatedBy: typeof values.generatedBy === 'string' && values.generatedBy.trim()
      ? values.generatedBy.trim()
      : undefined,
    generatedFrom: dateBoundary(generatedAt.from, false),
    generatedTo: dateBoundary(generatedAt.to, true),
    sort: HISTORY_SORT_FIELDS[activeSort?.id ?? 'generatedAt'] ?? 'generated_at',
    sortDirection: activeSort?.desc === false ? 'asc' : 'desc',
  }
}

export function useDocumentHistoryFilters(pageSize: number) {
  const t = useT()
  const [page, setPage] = React.useState(1)
  const [values, setValues] = React.useState<FilterValues>({})
  const [sorting, setSorting] = React.useState<SortingState>(DEFAULT_SORTING)
  const filters = React.useMemo(() => buildDocumentHistoryFilterDefinitions(t), [t])
  const query = React.useMemo(
    () => buildDocumentHistoryQuery(values, sorting, page, pageSize),
    [page, pageSize, sorting, values],
  )
  const apply = React.useCallback((nextValues: FilterValues) => {
    setValues(nextValues)
    setPage(1)
  }, [])
  const clear = React.useCallback(() => {
    setValues({})
    setPage(1)
  }, [])
  const changeSorting = React.useCallback((nextSorting: SortingState) => {
    setSorting(nextSorting.length ? nextSorting : DEFAULT_SORTING)
    setPage(1)
  }, [])
  const filterBarProps: Pick<FilterBarProps, 'filters' | 'values' | 'onApply' | 'onClear'> = {
    filters,
    values,
    onApply: apply,
    onClear: clear,
  }

  return {
    query,
    filterBarProps,
    page,
    setPage,
    sorting,
    setSorting: changeSorting,
  }
}
